### ISSUE TITLE
IllegalArgumentException because WorkbenchPlugin.getDefault().getDecoratorManager() null

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#100]
when i run FileSystemResourceManagerTest i now sometimes see in the output:
```
java.lang.IllegalArgumentException
	at org.eclipse.core.commands.common.EventManager.addListenerObject(EventManager.java:59)
	at org.eclipse.jface.viewers.BaseLabelProvider.addListener(BaseLabelProvider.java:31)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition$1.run(LightweightDecoratorDefinition.java:125)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.internalGetDecorator(LightweightDecoratorDefinition.java:119)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorDefinition.decorate(LightweightDecoratorDefinition.java:240)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager$LightweightRunnable.run(LightweightDecoratorManager.java:105)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.decorate(LightweightDecoratorManager.java:360)
	at org.eclipse.ui.internal.decorators.LightweightDecoratorManager.getDecorations(LightweightDecoratorManager.java:346)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.queue(DecorationScheduler.java:419)
	at org.eclipse.ui.internal.decorators.DecorationScheduler$1.run(DecorationScheduler.java:397)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by jukzi** [comment]
was fixed with 09896c33f4fd5f0f479106729a6e734f7717eacb
