### ISSUE TITLE
Random failing ProcessConsoleTests

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#1033]
`ProcessConsoleTests#testProcessTerminationNotificationWithInputFile()` (and maybe other tests in `ProcessConsoleTests`) are randomly failing when checking for logged errors during teardown, e.g.: https://github.com/eclipse-platform/eclipse.platform/pull/1031/checks?check_run_id=19741209418

```
Test triggered errors. expected:<0> but was:<1>
java.lang.AssertionError: Test triggered errors. expected:<0> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.eclipse.debug.tests.console.ProcessConsoleTests.tearDown(ProcessConsoleTests.java:111)
```

This issue is different from #770, in which some assertions during test run failed.

**Comment by HeikoKlare** [comment]
Logging the error instead of the numer has now reveled the actual error: 
```
Status ERROR: org.eclipse.debug.ui code=120 Error logged from Debug UI:  java.io.IOException: Stream Closed
```

See this build: https://github.com/eclipse-platform/eclipse.platform/actions/runs/8705248821/job/23875244761
```
2024-04-16T12:24:06.9724917Z org.eclipse.debug.tests.console.ProcessConsoleTests.testProcessTerminationNotificationWithInputFile -- Time elapsed: 0.074 s <<< FAILURE!
2024-04-16T12:24:06.9726649Z java.lang.AssertionError: 
2024-04-16T12:24:06.9727144Z [logged errors] 
2024-04-16T12:24:06.9728308Z Expecting empty but was: [Status ERROR: org.eclipse.debug.ui code=120 Error logged from Debug UI:  java.io.IOException: Stream Closed]
2024-04-16T12:24:06.9730279Z 	at org.eclipse.debug.tests.console.ProcessConsoleTests.tearDown(ProcessConsoleTests.java:111)
```

**Comment by HeikoKlare** [comment]
The recent failure shows that now the error is logged, but the stack trace that would allow to identify in which code the error occurred is missing. There are multiple places in org.eclipse.debug.ui (and also the potential source `ProcessConsole`) where an IOException because of a closed stream might occur. I have provided #1317 to improve log output with the strack trace to identify the line of code in which the error occurs.

**Comment by HeikoKlare** [comment]
First log for this failing test from #1317:
``` Expecting empty but was: ["Status ERROR: org.eclipse.debug.ui code=120 Error logged from Debug UI:  java.io.IOException: Stream Closed
Stack trace: java.base/java.io.FileInputStream.readBytes(Native Method)
java.base/java.io.FileInputStream.read(FileInputStream.java:263)
org.eclipse.debug.internal.ui.views.console.ProcessConsole$InputReadJob.run(ProcessConsole.java:909)
org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)"]
```

**Comment by iloveeclipse** [comment]
I haven't seen this failing recently. Should it be closed?

**Comment by HeikoKlare** [comment]
The last linked failure is from just a bit more than a month ago (https://github.com/eclipse-platform/eclipse.platform/pull/2406#issuecomment-3709320495. As that happened after the latest changes to `ProcessConsoleTests`, I guess the issue is still present.

_Edit:_ failed again just today: https://github.com/eclipse-platform/eclipse.platform/pull/2468/checks?check_run_id=64724142177

**Comment by iloveeclipse** [comment]
I haven't seen last failure stack, but looking at one provided here it seems that the inputstream was still running while teardown. So let assume this is the main issue, fix would be something like https://github.com/eclipse-platform/eclipse.platform/pull/2475.

**Comment by iloveeclipse** [comment]
Still failing testProcessTerminationNotificationWithInputFile

https://download.eclipse.org/eclipse/downloads/drops4/I20260304-1800/testresults/html/org.eclipse.debug.tests_ep440I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

```
java.lang.AssertionError: [logged errors]
Expecting empty but was: ["Status ERROR: org.eclipse.debug.ui code=120 Error logged from Debug UI: java.io.IOException: Stream Closed
Stack trace: java.base/java.io.FileInputStream.readBytes(Native Method)
java.base/java.io.FileInputStream.read(FileInputStream.java:263)
org.eclipse.debug.internal.ui.views.console.ProcessConsole$InputReadJob.run(ProcessConsole.java:1009)
org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)"]
at org.eclipse.debug.tests.console.ProcessConsoleTests.tearDown(ProcessConsoleTests.java:127)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

**Comment by iloveeclipse** [comment]
To reproduce, put a breakpoint at `org.eclipse.debug.internal.ui.views.console.ProcessConsole.InputReadJob.run(IProgressMonitor)` line 1005 before `bytesRead = readingStream.read(buffer);` line and one at last line of `org.eclipse.debug.tests.console.ProcessConsoleTests.processTerminationTest(ILaunchConfiguration, boolean)`, then resume `InputReadJob` breakpoint after second breakpoint is hit.

Main thread closing input stream:
```
	at org.eclipse.debug.internal.ui.views.console.ProcessConsole.closeStreams(ProcessConsole.java:632)
	at org.eclipse.debug.internal.ui.views.console.ProcessConsole.init(ProcessConsole.java:669)
	at org.eclipse.ui.console.AbstractConsole.initialize(AbstractConsole.java:242)
	at org.eclipse.ui.console.AbstractConsole$Lifecycle.consolesAdded(AbstractConsole.java:64)
	at org.eclipse.ui.internal.console.ConsoleManager$ConsoleNotifier.run(ConsoleManager.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.console.ConsoleManager$ConsoleNotifier.notify(ConsoleManager.java:172)
	at org.eclipse.ui.internal.console.ConsoleManager.fireUpdate(ConsoleManager.java:248)
	at org.eclipse.ui.internal.console.ConsoleManager.addConsoles(ConsoleManager.java:215)
	at org.eclipse.debug.tests.console.ProcessConsoleTests.processTerminationTest(ProcessConsoleTests.java:312)
	at org.eclipse.debug.tests.console.ProcessConsoleTests.testProcessTerminationNotificationWithInputFile(ProcessConsoleTests.java:285)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

InputReadJob that will now read from the stream and throw if the other thread closes it right before:
```
	at org.eclipse.debug.internal.ui.views.console.ProcessConsole$InputReadJob.run(ProcessConsole.java:1009)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
