### ISSUE TITLE
Random failure of HelpServerInterrupt.testServerWithInterrupt

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#1035]
Failed on [this build](https://github.com/eclipse-platform/eclipse.platform/actions/runs/7245896854/job/19736800082) of #776 

```java
org.eclipse.ua.tests.help.webapp.HelpServerInterrupt.testServerWithInterrupt -- Time elapsed: 7.263 s <<< ERROR!
java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:288)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:314)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:355)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:808)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:826)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:761)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at org.eclipse.ua.tests.help.webapp.HelpServerInterrupt.checkServer(HelpServerInterrupt.java:114)
	at org.eclipse.ua.tests.help.webapp.HelpServerInterrupt.testServerWithInterrupt(HelpServerInterrupt.java:66)
...
```

Can this one be related to #776 itself? If yes, why did it only fail after so many runs?

**Comment by HeikoKlare** [comment]
This test has been randomly failing for quite some time. I think it is only a network issue occurring once in a while. There was some discussion on that, so I thought there already was an issue for that test, but it seems like the discussion happened somewhere else.

**Comment by fedejeanne** [comment]
You mean this one? https://github.com/eclipse-platform/eclipse.platform.ua/issues/82. If that's the one then I think it was another problem (that also let that test fail) because it was marked as fixed in February (https://github.com/eclipse-platform/eclipse.platform.ua/issues/82#issuecomment-1413835419) but the test still fails

**Comment by HeikoKlare** [comment]
The one I mean was far more recently (I guess within the last two months).

**Comment by fedejeanne** [comment]
It seems no one experienced this problem in a while.

Closing.
