### ISSUE TITLE
Random failing of HelpServerBinding.testInfocenterBinding

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#1037]
Failed on [this build](https://github.com/eclipse-platform/eclipse.platform/actions/runs/7245896854/job/19736800082) of #776 

```java
org.eclipse.ua.tests.help.webapp.HelpServerBinding.testInfocenterBinding -- Time elapsed: 5.973 s <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at org.eclipse.ua.tests.help.webapp.HelpServerBinding.testInfocenterBinding(HelpServerBinding.java:70)
...
```

**Comment by HeikoKlare** [comment]
This has the same root cause as #1035: localhost is not reachable.

**Comment by fedejeanne** [comment]
Seems to be stable now
