### ISSUE TITLE
Delete the project file should ask to remove the project from workspace

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform#1074]
Currently if I remove a git repository I getting asked if I want to remove the associated projects from the workspace.

If I delete a `.project` file (e.g. from git staging view or on the filesystem or Project/Package Explorer) it can happen that eclipse create an (empty) one again or complains that the file is missing.

I therefore think that deleting the `.project` file should trigger a similar action like when one deletes the project itself (e.g. select it in the project explorer and choose delete).

**Comment by jukzi** [comment]
I also suffer sometimes similar: When someone else deleted a project in the git repository the .project file is recreated and shown in git staging area.

**Comment by laeubi** [comment]
> I also suffer sometimes similar: When someone else deleted a project in the git repository the .project file is recreated and shown in git staging area.

Guess how I found out :-D

**Comment by merks** [comment]
Yes it’s kind of annoying. Better the project is closed than to recreate a .project file.

**Comment by mickaelistria** [comment]
> If I delete a .project file (e.g. from git staging view or on the filesystem or Project/Package Explorer) it can happen that eclipse create an (empty) one again or complains that the file is missing.

I'm curious about that. Did you manage to get steps to reproduce and a stack trace about what re-creates the .project ?
Note that this topic has relations with https://github.com/eclipse-platform/eclipse.platform/issues/202

I agree with @merks that closing the project without notice is probably best, so people can delete or try to reopen it when needed, without popup to interrupt them on a branch switch.

**Comment by laeubi** [comment]
Just use any eclipse-platform repo:

1. create a new branch (`DELETE_TEST`) and delete a project, commit everything
2. switch to the main branch and import the just deleted project
3. Now right click on the repo and choose team switch > DELETE_TEST

You will end up with a closed project and a dirty working tree, eclipse probably also complains that the important project info was deleted and instead it created a dummy. Now you can switch back and probably now get complains from git that your need to commit or revert your "changes".

I think the main problem is that a closed project is even needing a physical .project file.

From users POV I would want if project file is removed (ResourceChangeListener?) the project either removed from the workspace completely or a closed project does not create a dummy file.

**Comment by laeubi** [comment]
The same of course can happen if you pull a change from someone else that deleted a project, by the way it would be really great if Egit could "plug in" somehow in eclipse to "help" with managing the projects, that's really a bit frustrating when switching between branches that have added/deleted projects, for example it would of course be nice if I switch to the other branch I'm getting asked if I wanted the just delted / closed project to be imported/added back ...

**Comment by Bananeweizen** [comment]
> it would be really great if Egit could "plug in" somehow in eclipse to "help" with managing the projects

\***sigh**\*
it does that.
![grafik](https://github.com/eclipse-platform/eclipse.platform/assets/406876/ed98ed75-4331-41ce-9bae-47b8279db040)

**Comment by laeubi** [comment]
> it does that.

Than it obviously not work ... or does something different. I have defiantly enabled this option on my Tycho workspace but it never has made anything better nor I noticed anything similar on other projects where I regularly switch branches...

**Comment by laeubi** [comment]
Just a recent example if one want to try it out, [here I have deleted a now obsolete project](https://github.com/eclipse-equinox/p2/pull/458), pulling the p2 repo in my IDE after the change was merged results in:

![grafik](https://github.com/eclipse-platform/eclipse.platform/assets/1331477/73ad646b-ab84-483b-8782-dcfbe8367f3d)

the stacktrace in the error log is this:

```
org.eclipse.core.internal.resources.ResourceException: Errors occurred while refreshing resources with the local file system.
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:1024)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:1004)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1601)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:227)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Contains: The project description file (.project) for 'org.eclipse.equinox.p2.tests.reconciler.product' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
java.lang.Exception: The project description file (.project) for 'org.eclipse.equinox.p2.tests.reconciler.product' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
	at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
	at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:951)
	at org.eclipse.core.internal.resources.Project.updateDescription(Project.java:1420)
	at org.eclipse.core.internal.resources.File.updateMetadataFiles(File.java:402)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.visit(RefreshLocalVisitor.java:306)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:119)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:1021)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:1004)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1601)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:227)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I now have a dirty working tree with an empty project file created:

![grafik](https://github.com/eclipse-platform/eclipse.platform/assets/1331477/b1981e82-e22c-42ef-9b66-a233f4e71d96)

and the project remains in the workspace:
![grafik](https://github.com/eclipse-platform/eclipse.platform/assets/1331477/d93d37c1-3095-45cb-ac49-50db1f84425e)

Git tracking of projects is enabled
![grafik](https://github.com/eclipse-platform/eclipse.platform/assets/1331477/afc5b1ae-f068-4e1d-9305-134325d7e3ed)
