### ISSUE TITLE
IllegalArgumentException when creating patch containing new files

### ISSUE THREAD

**Issue by ptziegler** [eclipse-platform/eclipse.platform#1159]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

- Check out a project from SVN (via Subclipse)
- Create a new file
- Create a patch via "Team -> Create Patch"

I expected:

A patch containing all workspace diffs, without any errors.

But got:

The error dialog shown below.

## Here is some relevant log output

![image](https://github.com/eclipse-platform/eclipse.platform/assets/70652978/30ba9751-28c6-4fb1-8bfc-73513bfd28f6)

From `<workspace>/.metadata/.log`
```
java.lang.IllegalArgumentException: 0
	at org.eclipse.team.internal.ui.mapping.ResourceDiffCompareInput.getCompareKind(ResourceDiffCompareInput.java:64)
	at org.eclipse.team.ui.synchronize.AbstractSynchronizeLabelProvider.getCompareKind(AbstractSynchronizeLabelProvider.java:146)
	at org.eclipse.team.ui.synchronize.AbstractSynchronizeLabelProvider.getCompareImage(AbstractSynchronizeLabelProvider.java:131)
	at org.eclipse.team.ui.synchronize.AbstractSynchronizeLabelProvider.decorateImage(AbstractSynchronizeLabelProvider.java:93)
	at org.eclipse.team.ui.synchronize.AbstractSynchronizeLabelProvider.getImage(AbstractSynchronizeLabelProvider.java:64)
	at org.tigris.subversion.subclipse.ui.util.ResourceSelectionTree$ResourceSelectionLabelProvider.getImage(ResourceSelectionTree.java:750)
	at org.eclipse.jface.viewers.WrappedViewerLabelProvider.getImage(WrappedViewerLabelProvider.java:101)
	at org.eclipse.jface.viewers.WrappedViewerLabelProvider.update(WrappedViewerLabelProvider.java:146)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:149)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:973)
	at org.eclipse.jface.viewers.CheckboxTreeViewer.doUpdateItem(CheckboxTreeViewer.java:124)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:131)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1046)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:426)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2111)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:867)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:845)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:611)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpandToLevel(AbstractTreeViewer.java:1815)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpandToLevel(AbstractTreeViewer.java:1826)
	at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1140)
	at org.eclipse.jface.viewers.AbstractTreeViewer.lambda$0(AbstractTreeViewer.java:1097)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1097)
	at org.eclipse.jface.viewers.AbstractTreeViewer.expandAll(AbstractTreeViewer.java:1058)
	at org.tigris.subversion.subclipse.ui.util.ResourceSelectionTree.createControls(ResourceSelectionTree.java:365)
	at org.tigris.subversion.subclipse.ui.util.ResourceSelectionTree.<init>(ResourceSelectionTree.java:144)
	at org.tigris.subversion.subclipse.ui.wizards.generatediff.PatchFileSelectionPage.createControl(PatchFileSelectionPage.java:299)
	at org.eclipse.jface.wizard.Wizard.createPageControls(Wizard.java:180)
	at org.eclipse.jface.wizard.WizardDialog.createPageControls(WizardDialog.java:744)
	at org.eclipse.jface.wizard.WizardDialog.createContents(WizardDialog.java:637)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.eclipse.jface.dialogs.Dialog.create(Dialog.java:1092)
	at org.eclipse.jface.window.Window.open(Window.java:788)
	at org.tigris.subversion.subclipse.ui.actions.GenerateDiffFileAction.execute(GenerateDiffFileAction.java:92)
	at org.tigris.subversion.subclipse.ui.actions.SVNAction.run(SVNAction.java:51)
...
```

## Tested under this environment:
* OS & version: Windows 10
* Eclipse IDE/Platform version (as shown in *Help > About*):
  * eclipse.buildId=4.31.0.I20240128-1800
  * java.version=21.0.1
  * java.vendor=Eclipse Adoptium
  * BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
  * Command-line arguments:  -os win32 -ws win32 -arch x86_64

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by ptziegler** [comment]
I suspect  https://github.com/eclipse-platform/eclipse.platform/commit/d2ed9d5ce7f06e0620f57537d835836555708a2a#diff-e185ba73e7ebf1f2d4084aa691094d14823ae93f3c91f1bc642c452eab63a716 to be the root of the problem.

An exception is thrown for an unexpected IDiff value (IDiff.NO_CHANGE). I think this case is missing, which sets compareKind to Differencer.NO_CHANGE.
The reason it worked before is because 0 (NO_CHANGE) was the initial value and used as default instead. Perhaps it even makes sense to use this instead of throwing an exception?

**Comment by merks** [comment]
Yes, please fix it to not throw an exception for NO_CHANGE.

**Comment by jukzi** [comment]
I could not reproduce the error with the given instructions. Some preconditions must be missing. I would like to reproduce it to understand why there is a IDiff without actual diff. If that is supposeed to happen then org.eclipse.team.core.diff.IDiff.getKind()  javadoc must be updated. And can org.eclipse.team.core.diff.IThreeWayDiff.getDirection() return 0 too?

**Comment by ptziegler** [comment]
> I could not reproduce the error with the given instructions. Some preconditions must be missing. I would like to reproduce it to understand why there is a IDiff without actual diff. If that is supposeed to happen then org.eclipse.team.core.diff.IDiff.getKind() javadoc must be updated. And can org.eclipse.team.core.diff.IThreeWayDiff.getDirection() return 0 too?

This seems to be a special behavior of the Subclipse SVN integration. I've updated the steps accordingly.

The "issue" seems to be that _NO_CHANGE_ if the default case of the [ResourceSelectionTree](https://github.com/subclipse/subclipse/blob/faec73788333473572ebb1cc1d2c2986d6ba7fe9/bundles/subclipse.ui/src/org/tigris/subversion/subclipse/ui/util/ResourceSelectionTree.java),  if no other change could be detected.
```
public int getKind() {
  int kind = IDiff.NO_CHANGE;
  if (syncInfoSet != null) {
	SyncInfo syncInfo = syncInfoSet.getSyncInfo(resource);
	if (syncInfo != null) {
	  int change = SyncInfo.getChange(syncInfo.getKind());
	  if (change == SyncInfo.CONFLICTING) kind = IThreeWayDiff.CONFLICTING;
	  else if (change == SyncInfo.CHANGE) kind = IDiff.CHANGE;
	  else if (change == SyncInfo.ADDITION) kind = IDiff.ADD;
	  else if (change == SyncInfo.DELETION) kind = IDiff.REMOVE;
	}
  } else {
	SVNStatusKind statusKind = (SVNStatusKind) statusMap.get(resource);
	if (statusKind == null) kind = IDiff.NO_CHANGE;
	else if (statusKind.equals(SVNStatusKind.CONFLICTED)) kind = IThreeWayDiff.CONFLICTING;
	else if (statusKind.equals(SVNStatusKind.MODIFIED)) kind = IDiff.CHANGE;
	else if (statusKind.equals(SVNStatusKind.ADDED)) kind = IDiff.ADD;
	else if (statusKind.equals(SVNStatusKind.DELETED)) kind = IDiff.REMOVE;
  }
  if (resource instanceof IContainer) return IDiff.REMOVE;
  return kind;
}
```
