### ISSUE TITLE
"Widget is disposed" error in tests triggering "Debug As..." menu

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#1202]
[I've finally managed](https://github.com/eclipse-equinox/p2/issues/450) to adopt our tests to 4.31 and immediately run into regression in "Debug As" menu.

The stack points to https://github.com/eclipse-platform/eclipse.platform.ui/commit/771d0b405910c4971123ffb46b09b9693d10af4e but the real issue is most likely coming from https://github.com/eclipse-platform/eclipse.platform/pull/1005/.

Most likely yet another indication of a problem with "async menus", related to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1068

The test simply opens Package Explorer on an application specific file and tries to expand / select "Debug As.." menu 

```
!ENTRY org.eclipse.ui 4 0 2024-02-13 16:08:19.387
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:565)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:480)
	at org.eclipse.swt.widgets.Menu.getItems(Menu.java:672)
	at org.eclipse.jface.action.ActionContributionItem.lambda$8(ActionContributionItem.java:1184)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1538)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1316)
	at org.eclipse.debug.ui.actions.ContextualLaunchAction.lambda$2(ContextualLaunchAction.java:306)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
```

**Comment by iloveeclipse** [comment]
With two revert PR's below the error is gone:
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/1679
- https://github.com/eclipse-platform/eclipse.platform/pull/1203
