### ISSUE TITLE
ConcurrentModificationException in InjectorImpl

### ISSUE THREAD

**Issue by chrismathis** [eclipse-platform/eclipse.platform#1256]
The RCP I'm working on crashes the first time it is started with an empty workspace.
The cause seems to be a ConcurrentModificationException in org.eclipse.e4.core.internal.di.InjectorImpl isAnnotationPresent().

It is called concurrently from the main thread and from a job that creates a hidden project for eGit. That in turn creates classes from extension points and loads activators from our plugins that do dependency-injection.

To be able to do dependency injection from different threads the annotationsPresent map should probably be synchronized.

https://github.com/eclipse-platform/eclipse.platform/blame/c74c80065aa91f5e2f03377aae1cd80928e48534/runtime/bundles/org.eclipse.e4.core.di/src/org/eclipse/e4/core/internal/di/InjectorImpl.java#L78

Stack 1 - main thread:
java.util.ConcurrentModificationException
    at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
    at org.eclipse.e4.core.internal.di.InjectorImpl.isAnnotationPresent(InjectorImpl.java:1002)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:943)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:938)
    at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:138)
    at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:385)
    at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:311)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:203)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultHeadlessContext(E4Application.java:481)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createDefaultContext(E4Application.java:495)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:213)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:577)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:555)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
    at at.bachmann.sc.core.Application.start(Application.java:143)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1459)

Stack 2 - from debugger - eGit
Thread [Worker-1: EGit Hidden Resources Clean-up] (Suspended (breakpoint at line 1002 in InjectorImpl))	
	InjectorImpl.isAnnotationPresent(AnnotatedElement, AnnotationLookup$AnnotationProxy) line: 1002	
	InjectorImpl.internalMake(Class<?>, PrimaryObjectSupplier, PrimaryObjectSupplier) line: 352	
	InjectorImpl.make(Class<T>, PrimaryObjectSupplier, PrimaryObjectSupplier) line: 325	
	ContextInjectionFactory.make(Class<T>, IEclipseContext, IEclipseContext) line: 228	
	PlcLibrariesPlugin.start(BundleContext) line: 37	
	BundleContextImpl$2.run() line: 818	
	BundleContextImpl$2.run() line: 1	
	AccessController.executePrivileged(PrivilegedExceptionAction<T>, AccessControlContext, Class<?>) line: not available	
	AccessController.doPrivileged(PrivilegedExceptionAction<T>) line: not available	
	BundleContextImpl.startActivator(BundleActivator) line: 810	
	BundleContextImpl.start() line: 767	
	EquinoxBundle.startWorker0() line: 1032	
	EquinoxBundle$EquinoxModule.startWorker() line: 371	
	EquinoxBundle$EquinoxModule(Module).doStart(Module$StartOptions...) line: 605	
	EquinoxBundle$EquinoxModule(Module).start(Module$StartOptions...) line: 468	
	SecureAction.start(Module, Module$StartOptions...) line: 513	
	EclipseLazyStarter.postFindLocalClass(String, Class<?>, ClasspathManager) line: 117	
	ClasspathManager.findLocalClass(String) line: 570	
	EquinoxClassLoader(ModuleClassLoader).findLocalClass(String) line: 335	
	BundleLoader.findLocalClass(String) line: 397	
	BundleLoader.findClass0(String, boolean, boolean) line: 500	
	BundleLoader.findClass(String) line: 416	
	EquinoxClassLoader(ModuleClassLoader).loadClass(String, boolean) line: 168	
	EquinoxClassLoader(ClassLoader).loadClass(String) line: not available	
	EquinoxBundle.loadClass(String) line: 622	
	EquinoxRegistryStrategy(RegistryStrategyOSGI).createExecutableExtension(RegistryContributor, String, String) line: 223	
	ExtensionRegistry.createExecutableExtension(RegistryContributor, String, String) line: 987	
	ConfigurationElement.createExecutableExtension(String) line: 255	
	ConfigurationElementHandle.createExecutableExtension(String) line: 65	
	ProjectVariableProviderManager$Descriptor.<init>(IExtension, IConfigurationElement) line: 46	
	ProjectVariableProviderManager.lazyInitialize() line: 105	
	ProjectVariableProviderManager.getDescriptors() line: 86	
	ProjectPathVariableManager.<init>(Resource) line: 58	
	Project(Resource).getPathVariableManager() line: 1939	
	LocationValidator.validateProjectLocationURI(IProject, URI) line: 357	
	Workspace.validateProjectLocationURI(IProject, URI) line: 2743	
	Project.checkDescription(IProject, IProjectDescription, boolean) line: 209	
	Project.assertCreateRequirements(IProjectDescription) line: 95	
	Project.create(IProjectDescription, int, IProgressMonitor) line: 305	
	HiddenResources.createProject(IProject, IProgressMonitor) line: 285	
	HiddenResources.getHiddenProject(IProgressMonitor) line: 271	
	HiddenResources.initialize(IProgressMonitor) line: 127	
	0x0000000801328000.run(IProgressMonitor) line: not available	
	Job$2.run(IProgressMonitor) line: 187	
	Worker.run() line: 63

**Comment by iloveeclipse** [comment]
Could you provide a patch?

**Comment by chrismathis** [comment]
Synchronizing the map fixes it for my RCP - see PR.
