### ISSUE TITLE
Console logs: High water mark must be greater than low water mark

### ISSUE THREAD

**Issue by guw** [eclipse-platform/eclipse.platform#1262]
I see the following in users logs quite frequently:

```
!ENTRY org.eclipse.ui.console 4 120 2024-03-19 16:53:40.505
!MESSAGE An exception occurred during console notification
!STACK 0
java.lang.IllegalArgumentException: High water mark must be greater than low water mark
	at org.eclipse.ui.console.IOConsole.setWaterMarks(IOConsole.java:250)
	at org.eclipse.debug.internal.ui.views.console.ProcessConsole.init(ProcessConsole.java:575)
	at org.eclipse.ui.console.AbstractConsole.initialize(AbstractConsole.java:242)
	at org.eclipse.ui.console.AbstractConsole$Lifecycle.consolesAdded(AbstractConsole.java:64)
	at org.eclipse.ui.internal.console.ConsoleManager$ConsoleNotifier.run(ConsoleManager.java:153)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.console.ConsoleManager$ConsoleNotifier.notify(ConsoleManager.java:174)
	at org.eclipse.ui.internal.console.ConsoleManager.fireUpdate(ConsoleManager.java:251)
	at org.eclipse.ui.internal.console.ConsoleManager.addConsoles(ConsoleManager.java:218)
	at org.eclipse.debug.internal.ui.views.console.ProcessConsoleManager$ConsoleCreation.run(ProcessConsoleManager.java:78)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Can the log message be improved to indicate what is contributing to the problem? Just logging it does not seem helpful.

**Comment by ricekwan** [comment]
on the version 2025-03,  pop the same error every time Run/Debug a project

![Image](https://github.com/user-attachments/assets/a12e3b3b-be10-4aa6-94b5-b27987b4a78d)

eclipse.buildId=4.35.0.20250306-0811
java.version=21.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_HK
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

`java.lang.IllegalArgumentException: High water mark must be greater than low water mark
	at org.eclipse.ui.console.IOConsole.setWaterMarks(IOConsole.java:251)
	at org.eclipse.debug.internal.ui.views.console.ProcessConsole.init(ProcessConsole.java:590)
	at org.eclipse.ui.console.AbstractConsole.initialize(AbstractConsole.java:242)
	at org.eclipse.ui.console.AbstractConsole$Lifecycle.consolesAdded(AbstractConsole.java:64)
	at org.eclipse.ui.internal.console.ConsoleManager$ConsoleNotifier.run(ConsoleManager.java:159)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.console.ConsoleManager$ConsoleNotifier.notify(ConsoleManager.java:180)
	at org.eclipse.ui.internal.console.ConsoleManager.fireUpdate(ConsoleManager.java:256)
	at org.eclipse.ui.internal.console.ConsoleManager.addConsoles(ConsoleManager.java:223)
	at org.eclipse.debug.internal.ui.views.console.ProcessConsoleManager$ConsoleCreation.run(ProcessConsoleManager.java:78)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
`
