### ISSUE TITLE
Deadlock in CharsetDeltaJob on workspace shutdown 

### ISSUE THREAD

**Issue by sratz** [eclipse-platform/eclipse.platform#1290]
We have been seeing increased amounts of deadlocks during workbench shutdown in our test suites in `org.eclipse.core.internal.resources.CharsetDeltaJob` (full [theaddump.txt](https://github.com/eclipse-platform/eclipse.platform/files/14903799/theaddump.txt)  attached).

The change in #631 seems to be the cause of this.

The relevant parts of the thread-dump are:
```
java.lang.Exception: ThreadDump for thread "Framework stop - Equinox Container: d9b0deee-892c-4a57-ba9c-02211f659f27"
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:45)
	at org.eclipse.core.internal.jobs.JobManager.join(JobManager.java:994)
	at org.eclipse.core.internal.jobs.InternalJob.join(InternalJob.java:355)
	at org.eclipse.core.runtime.jobs.Job.join(Job.java:531)
	at org.eclipse.core.internal.resources.CharsetDeltaJob.shutdown(CharsetDeltaJob.java:243)
	at org.eclipse.core.internal.resources.CharsetManager.shutdown(CharsetManager.java:503)
	at org.eclipse.core.internal.resources.Workspace.shutdown(Workspace.java:2558)
	at org.eclipse.core.internal.resources.Workspace.close(Workspace.java:721)
	at org.eclipse.core.resources.ResourcesPlugin$WorkspaceInitCustomizer.removedService(ResourcesPlugin.java:599)
	at org.eclipse.core.resources.ResourcesPlugin$WorkspaceInitCustomizer.removedService(ResourcesPlugin.java:1)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:973)
	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.untrack(AbstractTracked.java:342)
	at org.osgi.util.tracker.ServiceTracker.close(ServiceTracker.java:383)
	at org.eclipse.core.resources.ResourcesPlugin.stop(ResourcesPlugin.java:518)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:893)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.base@17.0.10/java.security.AccessController.executePrivileged(AccessController.java:807)
	at java.base@
17.0.10/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:885)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:1071)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:392)
	at org.eclipse.osgi.container.Module.doStop(Module.java:695)
	at org.eclipse.osgi.container.Module.stop(Module.java:554)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:2115)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1985)
	at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:281)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:222)
	at org.eclipse.osgi.container.Module.doStop(Module.java:695)
	at org.eclipse.osgi.container.Module.stop(Module.java:554)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:212)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:240)
	at java.base@17.0.10/java.lang.Thread.run(Thread.java:840)
java.lang.Exception: ThreadDump for thread "Worker-6: Reporting encoding changes."
	at java.base@17.0.10/java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:45)
	at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:191)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:125)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:100)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:87)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:125)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2398)
	at org.eclipse.core.internal.resources.CharsetDeltaJob.run(CharsetDeltaJob.java:205)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

@jukzi: Do you have an idea?

**Comment by jukzi** [comment]
I can take a look next week. A reproducer would help.

Jörg Kubitz
