### ISSUE TITLE
[mac] LinkTest failed on I20240514-1800: help/topic/org.eclipse.jdt.doc.user/nav/1_3 doens't exist.

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1370]
only on mac:
https://download.eclipse.org/eclipse/downloads/drops4/I20240514-1800/testresults/html/org.eclipse.ua.tests.doc_ep432I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
```
Expecting empty but was: ["Link from http://127.0.0.1:50948/help/topic/org.eclipse.jdt.doc.user/reference/views/breakpoints/ref-breakpoints_view.htm to ../../../nav/1 is broken: target URI http://127.0.0.1:50948/help/topic/org.eclipse.jdt.doc.user/nav/1 doens't exist.", "Link from http://127.0.0.1:50948/help/topic/org.eclipse.jdt.doc.user/reference/views/breakpoints/ref-breakpoints_view.htm to ../../../nav/1_3 is broken: target URI http://127.0.0.1:50948/help/topic/org.eclipse.jdt.doc.user/nav/1_3 doens't exist."]

java.lang.AssertionError:
Expecting empty but was: ["Link from http://127.0.0.1:50948/help/topic/org.eclipse.jdt.doc.user/reference/views/breakpoints/ref-breakpoints_view.htm to ../../../nav/1 is broken: target URI http://127.0.0.1:50948/help/topic/org.eclipse.jdt.doc.user/nav/1 doens't exist.",
"Link from http://127.0.0.1:50948/help/topic/org.eclipse.jdt.doc.user/reference/views/breakpoints/ref-breakpoints_view.htm to ../../../nav/1_3 is broken: target URI http://127.0.0.1:50948/help/topic/org.eclipse.jdt.doc.user/nav/1_3 doens't exist."]
at org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest.testAllLinks(LinkTest.java:103)
```

**Comment by jukzi** [comment]
got even worse on I20240515-1800:


```
Expecting empty but was: ["Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/gettingStarted/qs-WorkingWithExistingLayout2.htm to ../../../../../nav/4 is broken: target URI http://127.0.0.1:56668/../nav/4 doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/gettingStarted/qs-WorkingWithExistingLayout2.htm to ../../../../../nav/4_3 is broken: target URI http://127.0.0.1:56668/../nav/4_3 doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/gettingStarted/qs-WorkingWithExistingLayout2.htm to ../../../../../nav/4_3_0 is broken: target URI http://127.0.0.1:56668/../nav/4_3_0 doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/gettingStarted/qs-WorkingWithExistingLayout2.htm to ../../../../../nav/4_3_0_0 is broken: target URI http://127.0.0.1:56668/../nav/4_3_0_0 doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/reference/preferences/run-debug/ref-view_management.htm to ../../../../../../nav/1 is broken: target URI http://127.0.0.1:56668/nav/1 doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/reference/preferences/run-debug/ref-view_management.htm to ../../../../../../nav/1_4 is broken: target URI http://127.0.0.1:56668/nav/1_4 doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/reference/preferences/run-debug/ref-view_management.htm to ../../../../../../nav/1_4_4 is broken: target URI http://127.0.0.1:56668/nav/1_4_4 doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/reference/preferences/run-debug/ref-view_management.htm to ../../../../../../topic/org.eclipse.jdt.doc.user/reference/preferences/java/debug/ref-debug.htm is broken: target URI http://127.0.0.1:56668/topic/org.eclipse.jdt.doc.user/reference/preferences/java/debug/ref-debug.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/reference/preferences/run-debug/ref-view_management.htm to ../../../../../../topic/org.eclipse.jdt.doc.user/reference/preferences/ref-preferences-java.htm is broken: target URI http://127.0.0.1:56668/topic/org.eclipse.jdt.doc.user/reference/preferences/ref-preferences-java.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../../../nav/1 is broken: target URI http://127.0.0.1:56668/../../nav/1 doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../../../nav/1_4 is broken: target URI http://127.0.0.1:56668/../../nav/1_4 doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../../../nav/1_4_4 is broken: target URI http://127.0.0.1:56668/../../nav/1_4_4 doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../../../topic/org.eclipse.jdt.doc.user/reference/preferences/ref-preferences-java.htm is broken: target URI http://127.0.0.1:56668/../../topic/org.eclipse.jdt.doc.user/reference/preferences/ref-preferences-java.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/cdebugger.htm is broken: target URI http://127.0.0.1:56668/concepts/cdebugger.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/clocdbug.htm is broken: target URI http://127.0.0.1:56668/concepts/clocdbug.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/concept-classpath-variables.htm is broken: target URI http://127.0.0.1:56668/concepts/concept-classpath-variables.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/concept-java-perspective.htm is broken: target URI http://127.0.0.1:56668/concepts/concept-java-perspective.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/concept-java-views.htm is broken: target URI http://127.0.0.1:56668/concepts/concept-java-views.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/cremdbug.htm is broken: target URI http://127.0.0.1:56668/concepts/cremdbug.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../reference/preferences/java/debug/ref-debug.htm is broken: target URI http://127.0.0.1:56668/reference/preferences/java/debug/ref-debug.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../reference/preferences/java/debug/ref-execution_environments.htm is broken: target URI http://127.0.0.1:56668/reference/preferences/java/debug/ref-execution_environments.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../reference/preferences/run-debug/ref-run_debug.htm is broken: target URI http://127.0.0.1:56668/reference/preferences/run-debug/ref-run_debug.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../reference/ref-properties-source-attachment.htm is broken: target URI http://127.0.0.1:56668/reference/ref-properties-source-attachment.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-add_new_jre.htm is broken: target URI http://127.0.0.1:56668/tasks/task-add_new_jre.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-assign_default_jre.htm is broken: target URI http://127.0.0.1:56668/tasks/task-assign_default_jre.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-choose_config_jre.htm is broken: target URI http://127.0.0.1:56668/tasks/task-choose_config_jre.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-launching_java_program.htm is broken: target URI http://127.0.0.1:56668/tasks/task-launching_java_program.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-running_and_debugging.htm is broken: target URI http://127.0.0.1:56668/tasks/task-running_and_debugging.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-using_external_null_annotations.htm is broken: target URI http://127.0.0.1:56668/tasks/task-using_external_null_annotations.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/tasks-JREs.htm is broken: target URI http://127.0.0.1:56668/tasks/tasks-JREs.htm doens't exist.", "Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/tasks-deleteJRE.htm is broken: target URI http://127.0.0.1:56668/tasks/tasks-deleteJRE.htm doens't exist."]

java.lang.AssertionError:
Expecting empty but was: ["Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/gettingStarted/qs-WorkingWithExistingLayout2.htm to ../../../../../nav/4 is broken: target URI http://127.0.0.1:56668/../nav/4 doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/gettingStarted/qs-WorkingWithExistingLayout2.htm to ../../../../../nav/4_3 is broken: target URI http://127.0.0.1:56668/../nav/4_3 doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/gettingStarted/qs-WorkingWithExistingLayout2.htm to ../../../../../nav/4_3_0 is broken: target URI http://127.0.0.1:56668/../nav/4_3_0 doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/gettingStarted/qs-WorkingWithExistingLayout2.htm to ../../../../../nav/4_3_0_0 is broken: target URI http://127.0.0.1:56668/../nav/4_3_0_0 doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/reference/preferences/run-debug/ref-view_management.htm to ../../../../../../nav/1 is broken: target URI http://127.0.0.1:56668/nav/1 doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/reference/preferences/run-debug/ref-view_management.htm to ../../../../../../nav/1_4 is broken: target URI http://127.0.0.1:56668/nav/1_4 doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/reference/preferences/run-debug/ref-view_management.htm to ../../../../../../nav/1_4_4 is broken: target URI http://127.0.0.1:56668/nav/1_4_4 doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/reference/preferences/run-debug/ref-view_management.htm to ../../../../../../topic/org.eclipse.jdt.doc.user/reference/preferences/java/debug/ref-debug.htm is broken: target URI http://127.0.0.1:56668/topic/org.eclipse.jdt.doc.user/reference/preferences/java/debug/ref-debug.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.jdt.doc.user/reference/preferences/run-debug/ref-view_management.htm to ../../../../../../topic/org.eclipse.jdt.doc.user/reference/preferences/ref-preferences-java.htm is broken: target URI http://127.0.0.1:56668/topic/org.eclipse.jdt.doc.user/reference/preferences/ref-preferences-java.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../../../nav/1 is broken: target URI http://127.0.0.1:56668/../../nav/1 doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../../../nav/1_4 is broken: target URI http://127.0.0.1:56668/../../nav/1_4 doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../../../nav/1_4_4 is broken: target URI http://127.0.0.1:56668/../../nav/1_4_4 doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../../../topic/org.eclipse.jdt.doc.user/reference/preferences/ref-preferences-java.htm is broken: target URI http://127.0.0.1:56668/../../topic/org.eclipse.jdt.doc.user/reference/preferences/ref-preferences-java.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/cdebugger.htm is broken: target URI http://127.0.0.1:56668/concepts/cdebugger.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/clocdbug.htm is broken: target URI http://127.0.0.1:56668/concepts/clocdbug.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/concept-classpath-variables.htm is broken: target URI http://127.0.0.1:56668/concepts/concept-classpath-variables.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/concept-java-perspective.htm is broken: target URI http://127.0.0.1:56668/concepts/concept-java-perspective.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/concept-java-views.htm is broken: target URI http://127.0.0.1:56668/concepts/concept-java-views.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../concepts/cremdbug.htm is broken: target URI http://127.0.0.1:56668/concepts/cremdbug.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../reference/preferences/java/debug/ref-debug.htm is broken: target URI http://127.0.0.1:56668/reference/preferences/java/debug/ref-debug.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../reference/preferences/java/debug/ref-execution_environments.htm is broken: target URI http://127.0.0.1:56668/reference/preferences/java/debug/ref-execution_environments.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../reference/preferences/run-debug/ref-run_debug.htm is broken: target URI http://127.0.0.1:56668/reference/preferences/run-debug/ref-run_debug.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../reference/ref-properties-source-attachment.htm is broken: target URI http://127.0.0.1:56668/reference/ref-properties-source-attachment.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-add_new_jre.htm is broken: target URI http://127.0.0.1:56668/tasks/task-add_new_jre.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-assign_default_jre.htm is broken: target URI http://127.0.0.1:56668/tasks/task-assign_default_jre.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-choose_config_jre.htm is broken: target URI http://127.0.0.1:56668/tasks/task-choose_config_jre.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-launching_java_program.htm is broken: target URI http://127.0.0.1:56668/tasks/task-launching_java_program.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-running_and_debugging.htm is broken: target URI http://127.0.0.1:56668/tasks/task-running_and_debugging.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/task-using_external_null_annotations.htm is broken: target URI http://127.0.0.1:56668/tasks/task-using_external_null_annotations.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/tasks-JREs.htm is broken: target URI http://127.0.0.1:56668/tasks/tasks-JREs.htm doens't exist.",
"Link from http://127.0.0.1:56668/help/topic/org.eclipse.platform.doc.user/gettingStarted/qs-34a.xhtml to ../../../../tasks/tasks-deleteJRE.htm is broken: target URI http://127.0.0.1:56668/tasks/tasks-deleteJRE.htm doens't exist."]
at org.eclipse.ua.tests.doc.internal.linkchecker.LinkTest.testAllLinks(LinkTest.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```
https://download.eclipse.org/eclipse/downloads/drops4/I20240515-1800/testresults/html/org.eclipse.ua.tests.doc_ep432I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

**Comment by HeikoKlare** [comment]
Have not seen this failure for a long time and there are no recent reports of reoccurrences or references to this issue either.
