### ISSUE TITLE
Failed to read candidate component class; nested exception is java.lang.ArrayIndexOutOfBoundsException: Index 25697 out of bounds for length 447

### ISSUE THREAD

**Issue by thvinh2010** [eclipse-platform/eclipse.platform#1379]
I have a Java Web project. It was created with the following components:
・Spring Framework-3.1.1.RELEASE
・microsoft-jdk-17.0.11
・Tomcat 10.1.23
When I use eclipse-jee-2023-06-R-win32-x86_64, I can confirm that my project is working without any issues.
However, when I use eclipse-jee-2023-09-R-win32-x86_64 (or eclipse-jee-2024-03-R-win32-x86_64),
and start Tomcat 10.1, the log shows the following error:
----------------------------
2024/05/17 09:19:16.757 INFO  [                                ] FrameworkServlet 'DispatcherServlet': initialization started
2024/05/17 09:19:16.838 INFO  [                                ] Refreshing WebApplicationContext for namespace 'DispatcherServlet-servlet': startup date [Fri May 17 09:19:16 ICT 2024]; root of context hierarchy
2024/05/17 09:19:16.971 INFO  [                                ] Loading XML bean definitions from ServletContext resource [/WEB-INF/spring/servlet-context.xml]
2024/05/17 09:19:17.221 INFO  [                                ] JSR-250 'jakarta.annotation.ManagedBean' found and supported for component scanning
2024/05/17 09:19:17.293 ERROR [                                ] Context initialization failed
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [C:\Users\eclipse-workspace-2024-03\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps\WebServDemo\WEB-INF\classes\example\web\WebDemoController.class]; nested exception is java.lang.ArrayIndexOutOfBoundsException: Index 25697 out of bounds for length 447
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:261)
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:242)
	at org.springframework.context.annotation.ComponentScanBeanDefinitionParser.parse(ComponentScanBeanDefinitionParser.java:84)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:73)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1419)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1409)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:184)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:140)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:111)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:493)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:174)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:209)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:180)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:131)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:522)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:436)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:631)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:588)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:645)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:508)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:449)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:133)
	at jakarta.servlet.GenericServlet.init(GenericServlet.java:143)
	at jakarta.servlet.http.HttpServlet.init(HttpServlet.java:121) 
    at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:837)
    at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:794)
    at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:698)
    at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4172)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4458)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
    at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749)
    at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:772)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1203)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1193)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
    at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
    at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:749)
    at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
    at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
    at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:874)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
    at org.apache.catalina.startup.Catalina.start(Catalina.java:757)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:345)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:473)
    Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 25697 out of bounds for length 447
    at org.springframework.asm.ClassReader.readClass(Unknown Source)
    at org.springframework.asm.ClassReader.accept(Unknown Source)
    at org.springframework.asm.ClassReader.accept(Unknown Source)
    at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:54)
    at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:80)
    at org.springframework.core.type.classreading.CachingMetadataReaderFactory.getMetadataReader(CachingMetadataReaderFactory.java:101)
    at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:237)
    ... 59 more
--------------------------
Can I request support from the Eclipse support team?

**Comment by jukzi** [comment]
The given information does not have enough information.
"org.springframework.asm" is not maintained by this project. You should debug which java class to read does trigger that exception and ask at springframework. Only if you can show that the class produced is illegal you could create a issue against jdt. But by now it's more likely that springs ClassReader just can not handle it.

**Comment by thvinh2010** [comment]
> The given information does not have enough information. "org.springframework.asm" is not maintained by this project. You should debug which java class to read does trigger that exception and ask at springframework. Only if you can show that the class produced is illegal you could create a issue against jdt. But by now it's more likely that springs ClassReader just can not handle it.

Thank you for comment.
But I use eclipse-jee-2023-06-R-win32-x86_64, I can confirm that my project is working without any issues. In the project's lib folder, there is already a file org.springframework.asm-3.1.1.RELEASE.jar

**Comment by humphreygao** [comment]
你确定spring 3.1.1支持jdk17？你eclipse怎么选择jdk的？

**Comment by jukzi** [comment]
@humphreygao please use english only in this organization.
