### ISSUE TITLE
Eclipse 2024-06 fails to start: ClassNotFoundException: jakarta.servlet.ServletContainerInitializer

### ISSUE THREAD

**Issue by Mailaender** [eclipse-platform/eclipse.platform#1425]
```
Juni 14, 2024 8:42:17 AM org.apache.aries.spifly.BaseActivator log
INFORMATION: Registered provider ch.qos.logback.classic.spi.LogbackServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle ch.qos.logback.classic
08:42:18.881 [Start Level: Equinox Container: 7092f008-b331-44bc-8c9f-a7e6f4825c83] DEBUG org.eclipse.jgit.internal.util.ShutdownHook -- register org.eclipse.jgit.util.FS$FileStoreAttributes$$Lambda/0x000000010029c3e8@4f28cff5 with shutdown hook
08:42:18.881 [Start Level: Equinox Container: 7092f008-b331-44bc-8c9f-a7e6f4825c83] DEBUG org.eclipse.jgit.internal.util.ShutdownHook -- register org.eclipse.jgit.util.FS$FileStoreAttributes$$Lambda/0x000000010029c3e8@4f28cff5 with shutdown hook
08:43:44.355 [ForkJoinPool-1-worker-1] DEBUG org.eclipse.jgit.internal.util.ShutdownHook -- Cleanup org.eclipse.jgit.util.FS$FileStoreAttributes$$Lambda/0x000000010029c3e8@4f28cff5 during JVM shutdown
08:43:44.355 [ForkJoinPool-1-worker-1] DEBUG org.eclipse.jgit.internal.util.ShutdownHook -- Cleanup org.eclipse.jgit.util.FS$FileStoreAttributes$$Lambda/0x000000010029c3e8@4f28cff5 during JVM shutdown
org.osgi.framework.BundleException: Exception in org.apache.aries.spifly.dynamic.DynamicWeavingActivator.start() of bundle org.apache.aries.spifly.dynamic.bundle.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:854)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:775)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1057)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:387)
        at org.eclipse.osgi.container.Module.doStart(Module.java:639)
        at org.eclipse.osgi.container.Module.start(Module.java:498)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:463)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:482)
        at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.startBundles(ConfigApplier.java:562)
        at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.install(ConfigApplier.java:177)
        at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:189)
        at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:204)
        at org.eclipse.equinox.internal.p2.reconciler.dropins.ProfileSynchronizer.applyConfiguration(ProfileSynchronizer.java:805)
        at org.eclipse.equinox.internal.p2.reconciler.dropins.ProfileSynchronizer.synchronize(ProfileSynchronizer.java:150)
        at org.eclipse.equinox.internal.p2.reconciler.dropins.Activator.synchronize(Activator.java:434)
        at org.eclipse.equinox.internal.p2.reconciler.dropins.Activator.start(Activator.java:169)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:833)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:825)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:775)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1057)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:387)
        at org.eclipse.osgi.container.Module.doStart(Module.java:639)
        at org.eclipse.osgi.container.Module.start(Module.java:498)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:2074)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:143)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2065)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:2007)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1968)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1884)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
Caused by: java.lang.NoClassDefFoundError: jakarta/servlet/ServletContainerInitializer
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:293)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:774)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:691)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:657)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:637)
        at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:616)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:348)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:414)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:520)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:643)
        at org.apache.aries.spifly.ProviderBundleTrackerCustomizer.addingBundle(ProviderBundleTrackerCustomizer.java:143)
        at org.apache.aries.spifly.ProviderBundleTrackerCustomizer.addingBundle(ProviderBundleTrackerCustomizer.java:64)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:477)
        at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:257)
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:184)
        at org.osgi.util.tracker.BundleTracker.open(BundleTracker.java:161)
        at org.apache.aries.spifly.BaseActivator.start(BaseActivator.java:99)
        at org.apache.aries.spifly.dynamic.DynamicWeavingActivator.start(DynamicWeavingActivator.java:37)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:833)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:825)
        ... 33 more
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.ServletContainerInitializer cannot be found by ch.qos.logback.classic_1.5.0
        at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        ... 61 more
```

**Comment by merks** [comment]
The latest release packages have the 1.5.6 version of that bundle:
```
$unzip -l /d/stuff/eclipse-java-2024-06-R-win32-x86_64.zip  | grep ch.qos
   293697  2024-06-06 13:43   eclipse/plugins/ch.qos.logback.classic_1.5.6.jar
   609942  2024-06-06 13:43   eclipse/plugins/ch.qos.logback.core_1.5.6.jar
```
Can you provide more details about what exactly you installed and how you installed it?  Maybe you just did an update?

Maybe things are behaving poorly because of Java 21 issues?

https://www.eclipse.org/setups/sponsor/

**Comment by Mailaender** [comment]
I maintain https://aur.archlinux.org/packages/eclipse-rcp for @archlinux. Changing the default `java` did not seem to have any effect. Tried reinstalling, deleting both /usr/lib/eclipse and $HOME/.eclipse multiple times and `eclipse -clean` and `eclipse -clean -clearPersistedState` until I got a working IDE again that starts fast and where the PDE is available. First time I managed to get a stacktrace. I have similar trouble on updates, but I guess this is not reproducible.

**Comment by akurtakov** [comment]
AFAICT Eclipse RCP hasn't migrated to jakarta.servlet, it still uses javax.servlet and nothing in the RCP should be asking for jakarta.servlet.

**Comment by merks** [comment]
You can report problems about packages here

https://github.com/eclipse-packaging/packages/issues

More details is better.

**Comment by Mailaender** [comment]
Might be related to @sonarlint which I always have installed.

**Comment by HannesWell** [comment]
This looks very much like https://github.com/apache/aries/pull/233 and should be fixed with the latest version of aries.spifly. That version is actually shipped with Eclipse 2024-06.
