### ISSUE TITLE
FileSystemResourceManagerTest.testBug440110 fails on master

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1449]
https://ci.eclipse.org/platform/job/eclipse.platform/job/master/891/

```
org.eclipse.core.runtime.CoreException: Could not create file: //10a082372e35001f1ddcdca142372249/.project
	at org.eclipse.core.tests.internal.filesystem.ram.Policy.error(Policy.java:21)
	at org.eclipse.core.tests.internal.filesystem.ram.MemoryTree.openOutputStream(MemoryTree.java:288)
	at org.eclipse.core.tests.internal.filesystem.ram.MemoryFileStore.openOutputStream(MemoryFileStore.java:84)
	at org.eclipse.core.filesystem.IFileStore.write(IFileStore.java:498)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.write(FileSystemResourceManager.java:1356)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.internalWrite(FileSystemResourceManager.java:719)
	at org.eclipse.core.internal.resources.Project.writeDescription(Project.java:1466)
	at org.eclipse.core.internal.resources.Project.writeDescription(Project.java:1447)
	at org.eclipse.core.internal.resources.Project.create(Project.java:331)
	at org.eclipse.core.internal.resources.Project.create(Project.java:291)
	at org.eclipse.core.tests.internal.localstore.FileSystemResourceManagerTest.testBug440110(FileSystemResourceManagerTest.java:84)
```

**Comment by jukzi** [comment]
regression from https://github.com/eclipse-platform/eclipse.platform/pull/1448/files#diff-e75eeb675c9a0b2f8d26dbb8a24d98d2f49c8ec03f241f6a046417d4cd6c229bR719

in combination with 

https://github.com/eclipse-platform/eclipse.platform/pull/1446/files#diff-e75eeb675c9a0b2f8d26dbb8a24d98d2f49c8ec03f241f6a046417d4cd6c229bR1362

MemoryTree does not use error codes like EFS.ERROR_WRITE
