### ISSUE TITLE
OrderedLockTest.testComplex fails on alll platforms since I20220904-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#145]
OrderedLockTest.testComplex fails on alll platforms since I20220904-1800

Regression from https://github.com/eclipse-platform/eclipse.platform/pull/127

For example in https://download.eclipse.org/eclipse/downloads/drops4/I20220904-1800/testresults/html/org.eclipse.core.tests.runtime_ep426I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
testComplex(org.eclipse.core.tests.runtime.jobs.OrderedLockTest): failures 2 out of 10 tries. Last cause:java.lang.IllegalStateException: thread did not end

java.lang.AssertionError: testComplex(org.eclipse.core.tests.runtime.jobs.OrderedLockTest): failures 2 out of 10 tries. Last cause:java.lang.IllegalStateException: thread did not end
at org.eclipse.core.tests.runtime.jobs.RetryTestRule$1.evaluate(RetryTestRule.java:50)
```

**Comment by jukzi** [comment]
Please do not simply revert, i want to find out why... is there a logfile available from those builds?

Running locally i sometimes (its a test with random) see deadlocks like:
```
!ENTRY org.eclipse.core.jobs 4 2 2022-09-05 09:37:12.729
!MESSAGE Deadlock detected. All locks owned by thread Thread-31 will be suspended.
!STACK 0
java.lang.IllegalStateException
	at org.eclipse.core.internal.jobs.DeadlockDetector.reportDeadlock(DeadlockDetector.java:604)
	at org.eclipse.core.internal.jobs.DeadlockDetector.lockWaitStart(DeadlockDetector.java:408)
	at org.eclipse.core.internal.jobs.LockManager.addLockWaitThread(LockManager.java:146)
	at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:172)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:110)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:87)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable$RandomOrder.busy(LockAcquiringRunnable.java:79)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable.run(LockAcquiringRunnable.java:101)
	at java.base/java.lang.Thread.run(Thread.java:829)
!SUBENTRY 1 org.eclipse.core.jobs 4 2 2022-09-05 09:37:12.729
!MESSAGE Thread Thread-31 has locks: OrderedLock (5), OrderedLock (6) and is waiting for lock OrderedLock (4)
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1602)
	at org.eclipse.core.internal.jobs.DeadlockDetector.reportDeadlock(DeadlockDetector.java:618)
	at org.eclipse.core.internal.jobs.DeadlockDetector.lockWaitStart(DeadlockDetector.java:408)
	at org.eclipse.core.internal.jobs.LockManager.addLockWaitThread(LockManager.java:146)
	at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:172)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:110)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:87)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable$RandomOrder.busy(LockAcquiringRunnable.java:79)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable.run(LockAcquiringRunnable.java:101)
	at java.base/java.lang.Thread.run(Thread.java:829)

!SUBENTRY 1 org.eclipse.core.jobs 4 2 2022-09-05 09:37:12.730
!MESSAGE Thread Thread-26 has locks: OrderedLock (4) and is waiting for lock OrderedLock (6)
	at java.base@11.0.16/java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:45)
	at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:174)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:110)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:87)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable$$Lambda$743/0x00000013fb687040.run(Unknown Source)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable$RandomOrder.busy(LockAcquiringRunnable.java:79)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable.run(LockAcquiringRunnable.java:101)
	at java.base@11.0.16/java.lang.Thread.run(Thread.java:829)


```

But still the test passes after ~20s when run as plug-in test and passes after ~3s without logged errors when running as plain junit test

**Comment by iloveeclipse** [comment]
> is there a logfile available from those builds?

https://download.eclipse.org/eclipse/downloads/drops4/I20220904-1800/logs.php#console

**Comment by jukzi** [comment]
before the test fails it logs:

```
!ENTRY org.eclipse.core.jobs 4 2 2022-09-05 00:04:48.809
!MESSAGE Deadlock detected. All locks owned by thread testComplex # 1 will be suspended.
!STACK 0
java.lang.IllegalStateException
	at org.eclipse.core.internal.jobs.DeadlockDetector.reportDeadlock(DeadlockDetector.java:604)
	at org.eclipse.core.internal.jobs.DeadlockDetector.lockWaitStart(DeadlockDetector.java:408)
	at org.eclipse.core.internal.jobs.LockManager.addLockWaitThread(LockManager.java:146)
	at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:172)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:110)
	at org.eclipse.core.internal.jobs.LockManager$LockState.resume(LockManager.java:58)
	at org.eclipse.core.internal.jobs.LockManager.resumeSuspendedLocks(LockManager.java:316)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:111)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:87)
	at org.eclipse.core.tests.runtime.jobs.RandomTestRunnable.run(RandomTestRunnable.java:54)
!SUBENTRY 1 org.eclipse.core.jobs 4 2 2022-09-05 00:04:48.809
!MESSAGE Thread testComplex # 1 has locks: OrderedLock (108) and is waiting for lock OrderedLock (109)
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
	at org.eclipse.core.internal.jobs.DeadlockDetector.reportDeadlock(DeadlockDetector.java:618)
	at org.eclipse.core.internal.jobs.DeadlockDetector.lockWaitStart(DeadlockDetector.java:408)
	at org.eclipse.core.internal.jobs.LockManager.addLockWaitThread(LockManager.java:146)
	at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:172)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:110)
	at org.eclipse.core.internal.jobs.LockManager$LockState.resume(LockManager.java:58)
	at org.eclipse.core.internal.jobs.LockManager.resumeSuspendedLocks(LockManager.java:316)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:111)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:87)
	at org.eclipse.core.tests.runtime.jobs.RandomTestRunnable.run(RandomTestRunnable.java:54)

!SUBENTRY 1 org.eclipse.core.jobs 4 2 2022-09-05 00:04:48.809
!MESSAGE Thread testComplex # 2 has locks: OrderedLock (109) and is waiting for lock OrderedLock (108)
	at java.base@17.0.2/java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:45)
	at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:174)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:110)
	at org.eclipse.core.internal.jobs.LockManager$LockState.resume(LockManager.java:58)
	at org.eclipse.core.internal.jobs.LockManager.resumeSuspendedLocks(LockManager.java:316)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:111)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:87)
	at org.eclipse.core.tests.runtime.jobs.RandomTestRunnable.run(RandomTestRunnable.java:54)


!ENTRY org.eclipse.core.jobs 4 1 2022-09-05 00:04:53.894
!MESSAGE Worker thread ended job: Conflicting(3990), but still holds rule: ThreadJob(null,[IdentityRule(35),IdentityRule(35)])
!STACK 0
java.lang.IllegalStateException: Worker thread ended job: Conflicting(3990), but still holds rule: ThreadJob(null,[IdentityRule(35),IdentityRule(35)])
	at org.eclipse.core.internal.jobs.ImplicitJobs.endJob(ImplicitJobs.java:139)
	at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:119)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:83)

!ENTRY org.eclipse.core.jobs 4 2 2022-09-05 00:04:54.995
!MESSAGE An internal error occurred during: "Conflicting".
!STACK 0
org.eclipse.core.runtime.AssertionFailedException: null argument:transferRule without beginRule
	at org.eclipse.core.runtime.Assert.isNotNull(Assert.java:88)
	at org.eclipse.core.internal.jobs.ImplicitJobs.transfer(ImplicitJobs.java:264)
	at org.eclipse.core.internal.jobs.JobManager.transferRule(JobManager.java:1738)
	at org.eclipse.core.tests.runtime.jobs.Bug_311756$4.run(Bug_311756.java:108)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
-366
junit.framework.AssertionFailedError: Job still running after first join, executed: 1430, cpu: 1 expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:377)
	at org.eclipse.core.tests.runtime.jobs.Bug_574883.testReschedulingSomeMoreWork(Bug_574883.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.eclipse.test.EclipseTestRunner.runTests(EclipseTestRunner.java:226)
	at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:202)
	at org.eclipse.test.CoreTestApplication.runTests(CoreTestApplication.java:52)
	at org.eclipse.test.CoreTestApplication.run(CoreTestApplication.java:35)
	at org.eclipse.test.CoreTestApplication.start(CoreTestApplication.java:43)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
	at org.eclipse.core.launcher.Main.main(Main.java:44)

!ENTRY org.eclipse.core.runtime 2 1 2022-09-05 00:05:31.642
!MESSAGE Process returned non-zero code: 1
	Command: [
	eclipseArguments: {data=/home/jenkins/agent/workspace/ep426I-unit-cen64-gtk3-java17/tmp/workspace, os=linux, test=org.eclipse.core.tests.runtime.jobs.Bug_412138:testRunScenario, configuration=file:/home/jenkins/agent/workspace/ep426I-unit-cen64-gtk3-java17/workarea/I20220904-1800/eclipse-testing/test-eclipse/eclipse/configuration/, testpluginname=org.eclipse.core.tests.runtime, version=3, application=org.eclipse.pde.junit.runtime.coretestapplication, install=/home/jenkins/agent/workspace/ep426I-unit-cen64-gtk3-java17/workarea/I20220904-1800/eclipse-testing/test-eclipse/eclipse/, port=40013, vm=/home/jenkins/agent/workspace/ep426I-unit-cen64-gtk3-java17/java/jdk-17.0.2/bin/java, arch=x86_64, ws=gtk, nl=en_US}
	vmArguments: {}
	systemProperties: {eclipse.consoleLog=true, org.eclipse.update.reconcile=false}
]
```

"org.eclipse.core.runtime.AssertionFailedException: null argument:transferRule without beginRule"

sounds like a serious problem

**Comment by iloveeclipse** [comment]
Still there:
https://download.eclipse.org/eclipse/downloads/drops4/I20220919-0240/testResults.php

@jukzi : please could you either fix that or revert original change that caused this test to fail.

**Comment by jukzi** [comment]
now it's randomly failing 1/10
https://download.eclipse.org/eclipse/downloads/drops4/I20221004-0800/testresults/html/org.eclipse.core.tests.runtime_ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
https://download.eclipse.org/eclipse/downloads/drops4/I20221005-1800/testresults/html/org.eclipse.core.tests.runtime_ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
`
java.lang.AssertionError: testComplex(org.eclipse.core.tests.runtime.jobs.OrderedLockTest): failures 1 out of 10 tries. Last cause:java.lang.IllegalStateException: thread did not end`

**Comment by jukzi** [comment]
still randomly failing 1/10 on macosx
https://download.eclipse.org/eclipse/downloads/drops4/I20221020-1800/testresults/html/org.eclipse.core.tests.runtime_ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
