### ISSUE TITLE
LaunchTests.testProcessLaunchWithLongWorkingDirectory fails on Linux since I20240730-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#1488]
See https://download.eclipse.org/eclipse/downloads/drops4/I20240730-1800/testresults/html/org.eclipse.debug.tests_ep433I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

Most likely regression from https://github.com/eclipse-platform/eclipse.platform/pull/1477

```
Exception occurred executing command line.

org.eclipse.core.runtime.CoreException: Exception occurred executing command line.
at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:1015)
at org.eclipse.debug.tests.launching.LaunchTests.startProcessAndAssertOutputContains(LaunchTests.java:155)
at org.eclipse.debug.tests.launching.LaunchTests.testProcessLaunchWithLongWorkingDirectory(LaunchTests.java:150)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Caused by: java.io.IOException: Cannot run program "java" (in directory "/home/jenkins/agent/workspace/AutomatedTests/ep433I-unit-cen64-gtk3-java17/tmp/junit9299054611657995980/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name/subfolder-with-relativly-long-name"): error=2, No such file or directory
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at java.base/java.lang.Runtime.exec(Runtime.java:594)
at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:1011)
... 3 more
Caused by: java.io.IOException: error=2, No such file or directory
at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
... 6 more
```

**Comment by iloveeclipse** [comment]
@HannesWell : could you please check?

**Comment by HannesWell** [comment]
> @HannesWell : could you please check?

I can do it, probably this evening.
But I wonder why it fails only in I-builds?
Maybe it is sufficient to ensure the working-dir really exists, although I expected the JUnit TempFolder to create it.

**Comment by akurtakov** [comment]
Is there any progress on this one?

**Comment by HannesWell** [comment]
Sorry I forgot about this.
Just created https://github.com/eclipse-platform/eclipse.platform/pull/1511 as an attempt to fix this.

However I wonder how this can fail in I-builds when it passes in verification builds?
Do you have any idea? Can one of the Linux users reproduce it locally? Can Linux also have some kind of path length limit?

**Comment by iloveeclipse** [comment]
I've tried to make it failing locally but failed. I was using RHEL9.2

**Comment by HannesWell** [comment]
Thanks for trying.
Then lets have #1511 and if that doesn't help, I'll disable that test for Linux. It's actually only relevant for Windows any ways.

**Comment by HannesWell** [comment]
Lets keep this open until the fix has been verified.

**Comment by HannesWell** [comment]
Verified that for the latest I-build this issue is fixed.
