### ISSUE TITLE
100% CPU load in AbstractDataTreeNode.indexOfChild

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#152]
We've got a bug from customers on 4.15, but the code in question seem to be unchanged. No steps to reproduce.

Looks like binary search loops forever, which is an indicator that either the underlined array is not properly sorted or was changed during search.

```
"main" #1 prio=6 os_prio=0 cpu=1620231.88ms elapsed=265093.53s tid=0x00007f6348019000 nid=0x9bfe runnable  [0x00007f63504d9000]
   java.lang.Thread.State: RUNNABLE
	at org.eclipse.core.internal.dtree.AbstractDataTreeNode.indexOfChild(AbstractDataTreeNode.java:465)
	at org.eclipse.core.internal.dtree.AbstractDataTreeNode.childAtOrNull(AbstractDataTreeNode.java:254)
	at org.eclipse.core.internal.dtree.DeltaDataTree.lookup(DeltaDataTree.java:685)
	at org.eclipse.core.internal.watson.ElementTree.includes(ElementTree.java:533)
	- locked <0x00000010563b7e28> (a org.eclipse.core.internal.watson.ElementTree)
	at org.eclipse.core.internal.resources.Workspace.getResourceInfo(Workspace.java:1752)
	at org.eclipse.core.internal.resources.Resource.getResourceInfo(Resource.java:1181)
	at org.eclipse.core.internal.resources.Resource.checkAccessibleAndLocal(Resource.java:208)
	at org.eclipse.core.internal.resources.Resource.getSessionProperty(Resource.java:1186)
	at org.eclipse.ui.internal.ide.model.WorkbenchFile.getBaseImage(WorkbenchFile.java:56)
	at org.eclipse.ui.internal.ide.model.WorkbenchResource.getImageDescriptor(WorkbenchResource.java:46)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaElementImageProvider.getWorkbenchImageDescriptor(JavaElementImageProvider.java:193)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaElementImageProvider.computeDescriptor(JavaElementImageProvider.java:133)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaElementImageProvider.getImageLabel(JavaElementImageProvider.java:108)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaUILabelProvider.getImage(JavaUILabelProvider.java:145)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerLabelProvider.getImage(PackageExplorerLabelProvider.java:140)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.getImage(DelegatingStyledCellLabelProvider.java:198)
	at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.getImage(DecoratingStyledCellLabelProvider.java:171)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.update(DelegatingStyledCellLabelProvider.java:124)
	at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.update(DecoratingStyledCellLabelProvider.java:134)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:144)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:954)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:121)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.ui.internal.JFaceUtil$$Lambda$69/0x0000000840181c40.run(Unknown Source)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1032)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:427)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.ui.internal.JFaceUtil$$Lambda$69/0x0000000840181c40.run(Unknown Source)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:174)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2108)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createTreeItem(AbstractTreeViewer.java:848)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:826)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:604)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:774)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1685)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setSelectionToWidget(AbstractTreeViewer.java:2550)
	at org.eclipse.jface.viewers.StructuredViewer.setSelectionToWidget(StructuredViewer.java:1701)
	at org.eclipse.jface.viewers.AbstractTreeViewer.setSelectionToWidget(AbstractTreeViewer.java:3022)
	at org.eclipse.jface.viewers.StructuredViewer.setSelection(StructuredViewer.java:1657)
	at org.eclipse.jface.viewers.TreeViewer.setSelection(TreeViewer.java:1084)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerPart.showInput(PackageExplorerPart.java:1069)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerPart.editorActivated(PackageExplorerPart.java:1018)
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerPart$1.partActivated(PackageExplorerPart.java:232)
	at org.eclipse.ui.internal.WorkbenchPage$4.run(WorkbenchPage.java:4903)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4900)
	at org.eclipse.ui.internal.WorkbenchPage.access$3(WorkbenchPage.java:4876)
	at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:216)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:253)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:250)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:780)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:689)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:684)
	at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1270)
	at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3195)
```

**Comment by jukzi** [comment]
> Looks like binary search loops forever, which is an indicator that either the underlined array is not properly sorted or was changed during search.

In such a case it would rather return -1.
The only non terminal could be an integer overflow - unlikely that a node had node then MAX_INT/2 children. It's more likely, that while indexOfChild was 99,99% the hotspot it actually was started again and again.

**Comment by jukzi** [comment]
maybe related (JavaElementImageProvider.getWorkbenchImageDescriptor): https://bugs.eclipse.org/bugs/show_bug.cgi?id=569918


guess in the blue: org.eclipse.ui.internal.ide.model.WorkbenchFile.getBaseImage(IResource)
```
} catch (CoreException e) {
				// ignore - not having a cached image descriptor is not fatal

```

It may be fatal if the requested image is not cached due to exception and therefore the image is requested again and again

**Comment by iloveeclipse** [comment]
Ok, we've got another report and it looks like this was an issue with extremely huge folders in Eclipse (>10000 files in one folder), so it was not one call hanging but gazillions of calls from JFace to file system, GTK etc.

**Comment by jukzi** [comment]
> extremely huge folders in Eclipse (>10000 files in one folder)

so sad that programs can't handle 10000 files in 2022
