### ISSUE TITLE
"Invalid project description"

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#1619]
After updating my platform workspace i found the following exception in my log:
```
org.eclipse.oomph.resources.backend.BackendException: org.eclipse.core.internal.resources.ResourceException: Invalid project description.
	at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:158)
	at org.eclipse.oomph.targlets.core.WorkspaceIUInfo.importIntoWorkspace(WorkspaceIUInfo.java:108)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$3.run(WorkspaceIUImporter.java:176)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2457)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2477)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter.updateWorkspace(WorkspaceIUImporter.java:147)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$2.run(WorkspaceIUImporter.java:117)
	at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter.updateWorkspace(WorkspaceIUImporter.java:75)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$ImportProjectsJob.run(WorkspaceIUImporter.java:216)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.core.internal.resources.ResourceException: Invalid project description.
	at org.eclipse.core.internal.resources.Project.checkDescription(Project.java:211)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:95)
	at org.eclipse.core.internal.resources.Project.create(Project.java:305)
	at org.eclipse.core.internal.resources.Project.create(Project.java:291)
	at org.eclipse.oomph.resources.ResourcesUtil.importProject(ResourcesUtil.java:304)
	at org.eclipse.oomph.resources.backend.LocalBackendSystem.importIntoWorkspace(LocalBackendSystem.java:139)
	at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:146)
	... 10 more

```
![image](https://github.com/user-attachments/assets/f84f2446-3684-4fd3-9185-cc45432da56a)
![image](https://github.com/user-attachments/assets/59a6a17c-7c17-422a-bc24-96e02f244fe1)

At least i would like to know which project the exception is complaining about in the exception message.

**Comment by jukzi** [comment]
@merks Ed can you take a look please? The enhanced error message now blame some oomph related things:

```
org.eclipse.oomph.resources.backend.BackendException: org.eclipse.core.internal.resources.ResourceException: Invalid project description for project 'org.eclipse.platform.ui.setup' at 'file:/C:/Users/jkubitz/platform-2024-09-23/git/eclipse.platform.ui/releng/org.eclipse.ui.releng' 
	at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:158)
	at org.eclipse.oomph.targlets.core.WorkspaceIUInfo.importIntoWorkspace(WorkspaceIUInfo.java:108)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$3.run(WorkspaceIUImporter.java:176)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2457)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2477)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter.updateWorkspace(WorkspaceIUImporter.java:147)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$2.run(WorkspaceIUImporter.java:117)
	at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter.updateWorkspace(WorkspaceIUImporter.java:75)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$ImportProjectsJob.run(WorkspaceIUImporter.java:216)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.core.internal.resources.ResourceException: Invalid project description for project 'org.eclipse.platform.ui.setup' at 'file:/C:/Users/jkubitz/platform-2024-09-23/git/eclipse.platform.ui/releng/org.eclipse.ui.releng' 
	at org.eclipse.core.internal.resources.Project.checkDescription(Project.java:211)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:95)
	at org.eclipse.core.internal.resources.Project.create(Project.java:305)
	at org.eclipse.core.internal.resources.Project.create(Project.java:291)
	at org.eclipse.oomph.resources.ResourcesUtil.importProject(ResourcesUtil.java:304)
	at org.eclipse.oomph.resources.backend.LocalBackendSystem.importIntoWorkspace(LocalBackendSystem.java:139)
	at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:146)
	... 10 more
```

and

```
org.eclipse.oomph.resources.backend.BackendException: org.eclipse.core.internal.resources.ResourceException: Invalid project description for project 'org.eclipse.platform.sdk.setup' at 'file:/C:/Users/jkubitz/platform-2024-09-23/git/eclipse.platform.releng.aggregator/oomph' 
	at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:158)
	at org.eclipse.oomph.targlets.core.WorkspaceIUInfo.importIntoWorkspace(WorkspaceIUInfo.java:108)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$3.run(WorkspaceIUImporter.java:176)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2457)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2477)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter.updateWorkspace(WorkspaceIUImporter.java:147)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$2.run(WorkspaceIUImporter.java:117)
	at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter.updateWorkspace(WorkspaceIUImporter.java:75)
	at org.eclipse.oomph.targlets.internal.core.WorkspaceIUImporter$ImportProjectsJob.run(WorkspaceIUImporter.java:216)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.core.internal.resources.ResourceException: Invalid project description for project 'org.eclipse.platform.sdk.setup' at 'file:/C:/Users/jkubitz/platform-2024-09-23/git/eclipse.platform.releng.aggregator/oomph' 
	at org.eclipse.core.internal.resources.Project.checkDescription(Project.java:211)
	at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:95)
	at org.eclipse.core.internal.resources.Project.create(Project.java:305)
	at org.eclipse.core.internal.resources.Project.create(Project.java:291)
	at org.eclipse.oomph.resources.ResourcesUtil.importProject(ResourcesUtil.java:304)
	at org.eclipse.oomph.resources.backend.LocalBackendSystem.importIntoWorkspace(LocalBackendSystem.java:139)
	at org.eclipse.oomph.resources.backend.BackendContainer.importIntoWorkspace(BackendContainer.java:146)
	... 10 more

```

**Comment by merks** [comment]
Is there something off about the about the content of this file, i.e., the `.project` file located at `file:/C:/Users/jkubitz/platform-2024-09-23/git/eclipse.platform.ui/releng/org.eclipse.ui.releng`:

![image](https://github.com/user-attachments/assets/4f7bb53c-5166-434c-bbc0-b6fdb6730cf9)

![image](https://github.com/user-attachments/assets/27874584-f5a7-4d42-b300-36bc826c96a6)

This works fine for me and as you can see in the first picture, the project is imported into the workspace so the description file must be fine.

**Comment by jukzi** [comment]
i can't see the project in my package explorer even though git "import project" says it is already imported
![image](https://github.com/user-attachments/assets/2e5e1ada-90c0-4825-b4ec-81efe028c8d3)
![image](https://github.com/user-attachments/assets/d0d4410f-a6d7-4385-9c18-b908b9ec6c71)

**Comment by merks** [comment]
That leaves the workspace in kind of an inconsistent state.  I  suppose if you delete the project (without deleting it on disk), it will be imported with the correct name and the problem will go away...

**Comment by jukzi** [comment]
ok, thanks that helped fixing it.
![image](https://github.com/user-attachments/assets/27e47be1-274d-4a2a-8cd9-9c15fbfd6afc)
Maybe one should move the project path to stick with the pattern, that name and path are the same @HannesWell

**Comment by merks** [comment]
Yes, it's kind of confusing when the folder and IProject names are different...

**Comment by HannesWell** [comment]
> Maybe one should move the project path to stick with the pattern, that name and path are the same @HannesWell

This was done in an attempt to have a similar naming pattern for all projects containing setups without changing the paths of the setups. Because the latter is much more work, because it requires adjustments of the Oomph index. Not impossible, but more work.

**Comment by merks** [comment]
Yes, this is referenced via absolute URI from another setup, i.e., this one.  So if the path were to be changed, the URI would need to be changed here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/420650837e7249e2a58714554f074f22ff4be764/oomph/Platform.setup#L922

**Comment by basilevs** [comment]
So why does project name stick? Should not workspace re-read descriptions when opening a project?
