### ISSUE TITLE
random failing ParallelBuildChainTest.testDependentProjectsBuildSequentially

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#185]
https://download.eclipse.org/eclipse/downloads/drops4/I20220920-2240/testresults/html/org.eclipse.core.tests.resources_ep426I-unit-win32-java11_win32.win32.x86_64_11.html

```
junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertTrue(Assert.java:31)
at junit.framework.TestCase.assertTrue(TestCase.java:200)
at org.eclipse.core.tests.internal.builders.ParallelBuildChainTest.testDependentProjectsBuildSequentially(ParallelBuildChainTest.java:288)
```

relates to https://github.com/eclipse-platform/eclipse.platform/issues/157

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20221007-0230/testresults/html/org.eclipse.core.tests.resources_ep426I-unit-win32-java11_win32.win32.x86_64_11.html
