### ISSUE TITLE
[Win] 24 fails in IBuilds for resources since I20220926-1800

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#192]
I20220928-0600, I20220928-1800
https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.core.tests.resources_ep426I-unit-win32-java11_win32.win32.x86_64_11.html

logging misses [testProjectDescriptionFileModification] tearDown, but no exception logged

@iloveeclipse 
Why are the errors / exceptions not logged?

**Comment by iloveeclipse** [comment]
First failing test `org.eclipse.core.tests.resources.IResourceTest | testAcceptDoNotCheckExistence` and many following complain about `Resource '/openProject' already exists.` :
```
Resource '/openProject' already exists.

org.eclipse.core.internal.resources.ResourceException(/openProject)[374]: java.lang.Exception: Resource '/openProject' already exists.
at org.eclipse.core.internal.resources.ResourceException.provideStackTrace(ResourceException.java:42)
at org.eclipse.core.internal.resources.ResourceException.<init>(ResourceException.java:38)
at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:309)
at org.eclipse.core.internal.resources.Resource.checkDoesNotExist(Resource.java:296)
at org.eclipse.core.internal.resources.Project.assertCreateRequirements(Project.java:61)
at org.eclipse.core.internal.resources.Project.create(Project.java:272)
at org.eclipse.core.internal.resources.Project.create(Project.java:258)
at org.eclipse.core.internal.resources.Project.create(Project.java:253)
at org.eclipse.core.tests.resources.IResourceTest.setUp(IResourceTest.java:381)
```

**Comment by iloveeclipse** [comment]
> Why are the errors / exceptions not logged?

Because there were none.

That kind of issue happens because someone was optimistic to assume there is no need in teardown :-) 

See https://github.com/eclipse-platform/eclipse.platform/pull/199

I **hope** it was just the test order that changed for some obscure reason on the build machine. Locally, with "right" test order tests do not fail.

**Comment by jukzi** [comment]
again 24 fails, most of them "Resource '/openProject' already exists.":
https://download.eclipse.org/eclipse/downloads/drops4/S-4.26M1-202209281800/testresults/html/org.eclipse.core.tests.resources_ep426I-unit-win32-java11_win32.win32.x86_64_11.html

**Comment by iloveeclipse** [comment]
> again 24 fails, most of them "Resource '/openProject' already exists.":

This **was** in M1 build at 202209281800, so nothing new.

**Comment by jukzi** [comment]
oh, i clicked, the wrong link. thanks.

**Comment by HeikoKlare** [comment]
Closed as failures have not occurred recently.
