### ISSUE TITLE
random failing ParallelBuildChainTest.testDependentBuildConfigBuildSequentially

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#201]
https://download.eclipse.org/eclipse/downloads/drops4/I20221003-1800/testresults/html/org.eclipse.core.tests.resources_ep426I-unit-win32-java11_win32.win32.x86_64_11.html
```
junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertTrue(Assert.java:31)
at junit.framework.TestCase.assertTrue(TestCase.java:200)
at org.eclipse.core.tests.internal.builders.ParallelBuildChainTest.testDependentBuildConfigBuildSequentially(ParallelBuildChainTest.java:327)

```

relates to https://github.com/eclipse-platform/eclipse.platform/issues/185 (testDependentProjectsBuildSequentially )?

**Comment by HeikoKlare** [comment]
Closed as failure has not occurred recently.
