### ISSUE TITLE
[Tests] org.eclipse.ant.tests.ui.debug.PropertyTests fails with Did not find property: AAA

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-platform/eclipse.platform#21]
https://download.eclipse.org/eclipse/downloads/drops4/I20220530-0600/testresults/html/org.eclipse.ant.tests.ui_ep424I-unit-win32-java11_win32.win32.x86_64_11.html

testRuntimeProperties | Failure | Did not find property: AAAjunit.framework.AssertionFailedError: Did not find property: AAAat junit.framework.Assert.fail(Assert.java:57)at junit.framework.Assert.assertTrue(Assert.java:22)at junit.framework.Assert.assertNotNull(Assert.java:256)at junit.framework.TestCase.assertNotNull(TestCase.java:399)at org.eclipse.ant.tests.ui.debug.PropertyTests.assertProperty(PropertyTests.java:146)at org.eclipse.ant.tests.ui.debug.PropertyTests.runtimeProperties(PropertyTests.java:129)at org.eclipse.ant.tests.ui.debug.PropertyTests.testRuntimeProperties(PropertyTests.java:106)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at junit.framework.TestCase.runTest(TestCase.java:177)at junit.framework.TestCase.runBare(TestCase.java:142)at org.eclipse.ant.tests.ui.testplugin.AbstractAntUITest.runBare(AbstractAntUITest.java:132)at junit.framework.TestResult$1.protect(TestResult.java:122)at junit.framework.TestResult.runProtected(TestResult.java:142)at junit.framework.TestResult.run(TestResult.java:125)at junit.framework.TestCase.run(TestCase.java:130)at org.eclipse.ant.tests.ui.AbstractAntUIBuildTest.access$0(AbstractAntUIBuildTest.java:1)at org.eclipse.ant.tests.ui.AbstractAntUIBuildTest.lambda$0(AbstractAntUIBuildTest.java:46)at java.base/java.lang.Thread.run(Thread.java:829)
-- | -- | --

**Comment by HeikoKlare** [comment]
I have not seen this failure for a long time and there are no recent reports of reoccurrences or references to this issue either.
