### ISSUE TITLE
Random failing LinkedResourceWithPathVariableTest.testMoveFolder

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#217]
https://download.eclipse.org/eclipse/downloads/drops4/I20221007-0230/testresults/html/org.eclipse.core.tests.resources_ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
```
invocation 1 failed with org.eclipse.core.internal.resources.ResourceException: Resource '/OtherExistingProject/nonExistingFolderInOtherExistingProject' already exists.

java.lang.AssertionError: invocation 1 failed with org.eclipse.core.internal.resources.ResourceException: Resource '/OtherExistingProject/nonExistingFolderInOtherExistingProject' already exists.
at org.eclipse.core.tests.resources.TestPerformer.performTestRecursiveLoop(TestPerformer.java:97)
at org.eclipse.core.tests.resources.TestPerformer.performTestRecursiveLoop(TestPerformer.java:110)
at org.eclipse.core.tests.resources.TestPerformer.performTestRecursiveLoop(TestPerformer.java:110)
at org.eclipse.core.tests.resources.TestPerformer.performTest(TestPerformer.java:56)
at org.eclipse.core.tests.resources.LinkedResourceTest.testMoveFolder(LinkedResourceTest.java:1684)
at
```

probably relates to https://github.com/eclipse-platform/eclipse.platform/issues/107

**Comment by jukzi** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20221117-1330/testresults/html/org.eclipse.core.tests.resources_ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
`java.lang.AssertionError: invocation 7 failed with org.eclipse.core.internal.resources.ResourceException: Resource '/ExistingProject/existingFolderInExistingProject/nonExistingFolderInExistingFolder' already exists.
`
