### ISSUE TITLE
random failing JobTest.testSetThread

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#237]
https://download.eclipse.org/eclipse/downloads/drops4/I20221019-1800/testresults/html/org.eclipse.core.tests.runtime_ep426I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
```
10.0

junit.framework.AssertionFailedError: 10.0
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertNotNull(Assert.java:256)
at junit.framework.TestCase.assertNotNull(TestCase.java:399)
```

**Comment by jukzi** [comment]
Locally test passes when i execute the whole testclass but reproducible fails when only executing that single test with
```
java.lang.AssertionError: 2.0. Actual: Thread[main,5,main]
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failEquals(Assert.java:187)
	at org.junit.Assert.assertNotEquals(Assert.java:163)
	at org.eclipse.core.tests.runtime.jobs.JobTest.testSetThread(JobTest.java:1652)

```

**Comment by jukzi** [comment]
InternalJob.ABOUT_TO_RUN decodes to Job.RUNNING in InternalJob.getState()
ABOUT_TO_RUN is set in JobManager.nextJob() without setting a thread.
The thread is only set in JobManager.startJob(Worker) when the internal state ABOUT_TO_RUN is changed to RUNNING.
