### ISSUE TITLE
ObjectNotFoundException: Tree element '/' not found

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#243]
We observe this error with I20221020-1800 & our application tests.
This looks like regression from https://github.com/eclipse-platform/eclipse.platform/pull/114.

```
!ENTRY org.eclipse.core.resources 4 2 2022-10-21 09:24:38.127
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
org.eclipse.core.internal.dtree.ObjectNotFoundException: Tree element '/' not found.
	at org.eclipse.core.internal.dtree.AbstractDataTree.handleNotFound(AbstractDataTree.java:178)
	at org.eclipse.core.internal.dtree.DeltaDataTree.getData(DeltaDataTree.java:572)
	at org.eclipse.core.internal.events.ResourceDeltaFactory.createDelta(ResourceDeltaFactory.java:137)
	at org.eclipse.core.internal.events.ResourceDeltaFactory.computeDelta(ResourceDeltaFactory.java:64)
	at org.eclipse.core.internal.events.BuildManager.lambda$7(BuildManager.java:964)
	at org.eclipse.core.internal.events.BuildManager$DeltaCache.lambda$0(BuildManager.java:67)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at org.eclipse.core.internal.events.BuildManager$DeltaCache.computeIfAbsent(BuildManager.java:67)
	at org.eclipse.core.internal.events.BuildManager.getDeltaCached(BuildManager.java:958)
	at org.eclipse.core.internal.events.BuildManager.hasDelta(BuildManager.java:1296)
	at org.eclipse.core.internal.events.BuildManager.needsBuild(BuildManager.java:1288)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.resources 2 75 2022-10-21 09:24:38.128
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.core.resources 2 566 2022-10-21 09:24:38.128
!MESSAGE Tree element '/' not found.
!STACK 0
org.eclipse.core.internal.dtree.ObjectNotFoundException: Tree element '/' not found.
	at org.eclipse.core.internal.dtree.AbstractDataTree.handleNotFound(AbstractDataTree.java:178)
	at org.eclipse.core.internal.dtree.DeltaDataTree.getData(DeltaDataTree.java:572)
	at org.eclipse.core.internal.events.ResourceDeltaFactory.createDelta(ResourceDeltaFactory.java:137)
	at org.eclipse.core.internal.events.ResourceDeltaFactory.computeDelta(ResourceDeltaFactory.java:64)
	at org.eclipse.core.internal.events.BuildManager.lambda$7(BuildManager.java:964)
	at org.eclipse.core.internal.events.BuildManager$DeltaCache.lambda$0(BuildManager.java:67)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
	at org.eclipse.core.internal.events.BuildManager$DeltaCache.computeIfAbsent(BuildManager.java:67)
	at org.eclipse.core.internal.events.BuildManager.getDeltaCached(BuildManager.java:958)
	at org.eclipse.core.internal.events.BuildManager.hasDelta(BuildManager.java:1296)
	at org.eclipse.core.internal.events.BuildManager.needsBuild(BuildManager.java:1288)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:216)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:161)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:255)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by jukzi** [comment]
How to reproduce?

**Comment by iloveeclipse** [comment]
> How to reproduce?

I'm on it, extracting a self containing test

**Comment by jukzi** [comment]
my best guess for a project that had no data at root: a project that is deleted - which should not be build anyway
