### ISSUE TITLE
random failing OrderedLockTest.testSimple DNF

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#260]
"core.tests.runtime" timed out in OrderedLockTest.testSimple 

https://download.eclipse.org/eclipse/downloads/drops4/I20221107-1920/testresults/ep426I-unit-win32-java11_win32.win32.x86_64_11/org.eclipse.core.tests.runtime.AutomatedRuntimeTests.txt

```
java.lang.Exception: ThreadDump for thread "Thread-228"
	at java.base@11.0.15/java.lang.Object.wait(Native Method)
	at org.eclipse.core.internal.jobs.Semaphore.acquire(Semaphore.java:45)
	at org.eclipse.core.internal.jobs.OrderedLock.doAcquire(OrderedLock.java:174)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:110)
	at org.eclipse.core.internal.jobs.OrderedLock.acquire(OrderedLock.java:87)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable$$Lambda$474/0x0000000100576040.run(Unknown Source)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable$RandomOrder.busy(LockAcquiringRunnable.java:79)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable.run(LockAcquiringRunnable.java:101)
	at java.base@11.0.15/java.lang.Thread.run(Thread.java:829)

java.lang.Exception: ThreadDump for thread "main"
	at java.base@11.0.15/java.lang.Thread.yield(Native Method)
	at org.eclipse.core.tests.runtime.jobs.LockAcquiringRunnable$RandomOrder.waitForEnd(LockAcquiringRunnable.java:72)
	at org.eclipse.core.tests.runtime.jobs.OrderedLockTest.execute(OrderedLockTest.java:293)
	at org.eclipse.core.tests.runtime.jobs.OrderedLockTest.lambda$1(OrderedLockTest.java:74)
	at org.eclipse.core.tests.runtime.jobs.OrderedLockTest$$Lambda$484/0x0000000100578840.run(Unknown Source)
	at org.eclipse.core.internal.jobs.DeadlockDetector.runSilent(DeadlockDetector.java:606)
	at org.eclipse.core.tests.runtime.jobs.OrderedLockTest.testSimple(OrderedLockTest.java:66)
```

2022-11-08 02:37:46.657 core.tests.runtime tests startet
2022-11-08 02:37:50.735 starting DumpStackTracesTimer with timeout=7080000 at 2022-11-08 02:37:50 +0000
2022-11-08 02:38:43.007 testBeginRuleNoEnd logged something
2022-11-08 02:38:54.992 DumpStackTracesTimer almost reached timeout '7200000'
but that's only < 12sec.

Some error in time measurement?

**Comment by HeikoKlare** [comment]
Closed as failure has not occurred recently.
