### ISSUE TITLE
Job.schedule() sometimes either doesn't work or doesn't notify listeners about job is running

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#263]
Coming from https://github.com/eclipse-platform/eclipse.platform/issues/193#issuecomment-1307601512 and test case #262.

We have a regression in 4.26 job scheduling code.

The error case looks like this below.

The main thread can't proceed and waits (for a job to be scheduled?), and there are only two worker threads that just sleep. That was reproduced after "Starting 4276 round". 
In case it matters: I'm on RHEL 7.9 / 16 cores Xeon, 256 GB RAM, Java OpenJDK Temurin-17.0.4+8 (build 17.0.4+8).

org.eclipse.core.internal.jobs.JobManager.waiting & sleeping are empty.

sleepHint is 9223372036854775807 (InternalJob.T_INFINITE) matches the case that there is nothing to do.

After looking at the code & test I think there are following possibilities how we can get to the state in #262 :
1) The `job1.schedule();` didn't scheduled `job1`
2) The job was scheduled but didn't run
3) The job was executed but `running()` event was not sent to `job1` listener

Since the `JobManager.scheduleInternal(InternalJob, long, boolean)` looks pretty simple so 
- either `JobManager.doSchedule(InternalJob, long)` and later code 
- or `JobManager.startJob(Worker)` 
- or `JobListeners.waitAndSendEvents(InternalJob, boolean)` 
- or something completely different
 
could be our problem. 

```
"main" #1 prio=5 os_prio=0 cpu=43800.12ms elapsed=4423.25s
tid=0x00007ffff0026e40 nid=0x85ed in Object.wait()  [0x00007ffff7fb5000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.4/Native Method)
        - waiting on <no object reference available>
        at java.lang.Object.wait(java.base@17.0.4/Object.java:338)
        at org.eclipse.core.tests.runtime.jobs.GithubBug_193.twoNestedJobs(Unknown
Source)
        - locked <0x000000070dceb3e0> (a java.lang.Object)
        at org.eclipse.core.tests.runtime.jobs.GithubBug_193.testNestedSchedule(Unknown
Source)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.4/Native
Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.4/NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.4/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@17.0.4/Method.java:568)
        at junit.framework.TestCase.runTest(TestCase.java:177)
        at junit.framework.TestCase.runBare(TestCase.java:142)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:130)
        at junit.framework.TestSuite.runTest(TestSuite.java:241)
        at junit.framework.TestSuite.run(TestSuite.java:236)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
        at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
        at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
        at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:74)
        at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.start(CoreTestApplication.java:28)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.4/Native
Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.4/NativeMethodAccessorImpl.java:77)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.4/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@17.0.4/Method.java:568)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

```
"Worker-426" #484 prio=5 os_prio=0 cpu=1979.24ms elapsed=4314.56s
tid=0x00007ffe68003770 nid=0x8a24 in Object.wait()  [0x00007ffec46dd000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.4/Native Method)
        - waiting on <no object reference available>
        at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
        - locked <0x00000007026f2c38> (a
org.eclipse.core.internal.jobs.WorkerPool)
        at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

   Locked ownable synchronizers:
        - None
```

```
"Worker-598" #656 prio=5 os_prio=0 cpu=32.53ms elapsed=4274.55s
tid=0x00007ffff1145330 nid=0x8bb7 in Object.wait()  [0x00007fffa4aad000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(java.base@17.0.4/Native Method)
        - waiting on <no object reference available>
        at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
        - locked <0x00000007026f2c38> (a
org.eclipse.core.internal.jobs.WorkerPool)
        at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

   Locked ownable synchronizers:
        - None
```

See https://github.com/eclipse-platform/eclipse.platform/issues/193

**Comment by jukzi** [comment]
not an eclipse issue:
What happens is that syncObject.notify() happend before syncObject.wait() was ready to wake up and therefore the wait just does not wake up.
```
scheduled job_1_51(2431)
aboutToRun job_1_51(2431)
running job_1_51(2431)
schedule: job_2_51(2432)
scheduled job_2_51(2432)
notified: sync_51  <----- too early
wait for: sync_51  <----- too late
......................................................................................................................................................... (dummy jobs)
done job_1_51(2431)
aboutToRun job_2_51(2432)
running job_2_51(2432)
done job_2_51(2432)
=>FREEZE
```
( i added a IJobChangeListener to sysout the events)

I don't know if that a bug in JDK - at least it makes me wonder why that can happen but i can also see no guarantee in java.lang.Object.notify() that it does not return before wakeup happend or in java.lang.Object.wait() that another threads "synchronized" would wait until wait() is ready to listen for notify().

jdk-17.0.5.8

**Comment by laeubi** [comment]
wait/notify are very low level and should generally be avoided and replaced with proper high-level primitives because they are very error prone to use.

So "notify" can never be "too early" because you should only "wait" when there is something to wait for. So obviously in your example something is wrong on the wait side (because actually it should not need to wait) or the asumption that someone will ever notify is wrong.

**Comment by iloveeclipse** [comment]
The question not answered yet: why the test only fails on Eclipse 4.26, where same tests run successfully on same JVM / environment in 4.25? The only difference is Eclipse platform used. Note: we run tests a lot, every day/night, and hangs are only seen on the branch that uses 4.26 nightly builds.

**Comment by laeubi** [comment]
@jukzi you should print out the Thread as well, if it happens that the listener is called in the same thread that later waits, then any sync is useless because the same thread can enter sync block multiple times.

**Comment by jukzi** [comment]
> any sync is useless because the same thread can enter sync block multiple times.

thats it.
```
Starting 43 round
...........................................
schedule: job_1_43(2035)
scheduled job_1_43(2035) main
aboutToRun job_1_43(2035) main
running job_1_43(2035) main
schedule: job_2_43(2036) main
scheduled job_2_43(2036) main
notified: sync_43 main <-- MAIN
wait for: sync_43 main <-- MAIN
.................................................................................................................................
done job_1_43(2035) Worker-38: job_1_43
aboutToRun job_2_43(2036) Worker-41
running job_2_43(2036) Worker-41
done job_2_43(2036) Worker-41: job_2_43
```

**Comment by iloveeclipse** [comment]
OK, thanks for looking into, explanation with the "same thread notifies himself" makes sense.

This is indeed a regression from the Job framework behavior change (which thread dispatches which events) and explains why the code hangs on 4.26 only.

As I've wrote in https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/pull/64, it is a good example of a valid  code that worked all releases before isn't working anymore in 4.26 and I believe it should be added to the readme.

Unless you have an idea how to fix or workaround this regression **in the framework**, you can close this bug as "won't fix".

**Comment by laeubi** [comment]
Is there any hint in the API what thread listeners are notified?

**Comment by iloveeclipse** [comment]
> what thread listeners are notified?

What do you mean by "what"?  Did you mean "**on** what thread" listeners will be notified? 
No, this is not specified, so it is not an API breakage, but "only" behavior change.

**Comment by laeubi** [comment]
> > what thread listeners are notified?
> 
> What do you mean by "what"? Did you mean "**on** what thread" listeners will be notified? 

Yes, e.g.if it is always a different thread or might also be the calling thread, or actually any thread.... I think this is then similar to what @jukzi wrote about the UIJob and notification on the UI Thread.

**Comment by jukzi** [comment]
> Is there any hint in the API what thread listeners are notified?

It is undefined by API in which thread listeners are called. won't change that.
