### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "java.util.Queue.isEmpty()" because "job.eventQueue" is null

### ISSUE THREAD

**Issue by apupier** [eclipse-platform/eclipse.platform#270]
When upgrading to 2022-12, 2 of my tests are failing with this error:

```
java.lang.NullPointerException: Cannot invoke "java.util.Queue.isEmpty()" because "job.eventQueue" is null
    at org.eclipse.core.internal.jobs.JobListeners.waitAndSendEvents(JobListeners.java:58)
    at org.eclipse.core.internal.jobs.JobManager.waitEventsSend(JobManager.java:518)
    at org.eclipse.core.internal.jobs.JobManager.cancel(JobManager.java:324)
    at org.eclipse.core.internal.jobs.InternalJob.cancel(InternalJob.java:200)
    at org.eclipse.core.runtime.jobs.Job.cancel(Job.java:290)
    at org.fusesource.ide.launcher.debug.model.CamelDebugTarget.cleanJobs(CamelDebugTarget.java:354)
    at org.fusesource.ide.launcher.debug.model.CamelDebugTarget.terminate(CamelDebugTarget.java:345)
    at org.fusesource.ide.launcher.debug.model.CamelDebugTargetTest.testTerminateStatusForLocalDebug(CamelDebugTargetTest.java:60)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:79)
    at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:85)
    at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:39)
    at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```
version used: org.eclipse.core.jobs_3.13.200.v20221020-1350.jar

I do not understand how the `job.eventQueue` can be null given that `eventQueue` is final.

**Comment by apupier** [comment]
related code seems to have been updated recently https://github.com/eclipse-platform/eclipse.platform/commit/8186be140279bec9553cffdac31ed851f8344120

**Comment by iloveeclipse** [comment]
@apupier : your stack trace doesn't match master branch, ideally you would test with I20221102-0750+ build that contains latest changes in this area dc7bfe70caa56ad3a63b3181dad3364ec7498cf7.

**Comment by jukzi** [comment]
> I do not understand how the `job.eventQueue` can be null given that `eventQueue` is final.

Please provide a reproducer. The only way i am aware to get a null on a final is to reference it before initialization finished.

**Comment by jukzi** [comment]
closing as not reproducible
