### ISSUE TITLE
org.eclipse.core.tests.runtime.jobs.JobEventTest | testSleepOrderOfEvents fails on windows intermittently

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform#271]
org.eclipse.core.tests.runtime.jobs.JobEventTest | testSleepOrderOfEvents failed on windows in the build [I20221117-1330](https://download.eclipse.org/eclipse/downloads/drops4/I20221117-1330/testresults/html/org.eclipse.core.tests.runtime_ep426I-unit-win32-java11_win32.win32.x86_64_11.html) with the below error

```
java.lang.AssertionError: Race condition at Event 7 Job.run() in Thread 'Worker-659: testSleepOrderOfEvents'

java.lang.AssertionError: java.lang.AssertionError: Race condition at Event 7 Job.run() in Thread 'Worker-659: testSleepOrderOfEvents'
at org.eclipse.core.tests.runtime.jobs.OrderAsserter.lambda$0(OrderAsserter.java:143)
at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037)
at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054)
at org.eclipse.core.tests.runtime.jobs.OrderAsserter.assertNoErrors(OrderAsserter.java:142)
at org.eclipse.core.tests.runtime.jobs.JobEventTest.testSleepOrderOfEvents(JobEventTest.java:315) 
```

**Comment by iloveeclipse** [comment]
@jukzi : could you please take a look?

**Comment by jukzi** [comment]
The given link does not show that error which makes it impossible to analyze.

**Comment by iloveeclipse** [comment]
OK, the lost test fail can be seen here:
https://ci.eclipse.org/releng/job/AutomatedTests/job/ep426I-unit-win32-java11/33/#showFailuresLink

https://ci.eclipse.org/releng/job/AutomatedTests/job/ep426I-unit-win32-java11/33/testReport/junit/org.eclipse.core.tests.runtime.jobs/JobEventTest/testSleepOrderOfEvents/

**Comment by jukzi** [comment]
Race condition at Event 7 Job.run() in Thread 'Worker-659: testSleepOrderOfEvents'  with Event 6 IJobChangeEvent.running() in Thread 'Worker-660'


```
Caused by: java.lang.AssertionError: Race condition at Event 7 Job.run() in Thread 'Worker-659: testSleepOrderOfEvents'
	at org.eclipse.core.tests.runtime.jobs.OrderAsserter.addError(OrderAsserter.java:127)
	at org.eclipse.core.tests.runtime.jobs.OrderAsserter.expect(OrderAsserter.java:101)
	at org.eclipse.core.tests.runtime.jobs.OrderAsserter.expect(OrderAsserter.java:68)
	at org.eclipse.core.tests.runtime.jobs.JobEventTest$5.run(JobEventTest.java:259)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.AssertionError: Race condition at Event 7 Job.run()
	at org.eclipse.core.tests.runtime.jobs.OrderAsserter.expect(OrderAsserter.java:84)
	... 3 more
Caused by: java.lang.IllegalStateException: Race condition with Event 6 IJobChangeEvent.running() in Thread 'Worker-660'
	at org.eclipse.core.tests.runtime.jobs.OrderAsserter.expect(OrderAsserter.java:89)
	at org.eclipse.core.tests.runtime.jobs.OrderAsserter.expect(OrderAsserter.java:68)
	at org.eclipse.core.tests.runtime.jobs.JobEventTest$6.running(JobEventTest.java:298)
	at org.eclipse.core.internal.jobs.JobListeners.sendEvent(JobListeners.java:138)
	at org.eclipse.core.internal.jobs.JobListeners.sendEventsAsync(JobListeners.java:118)
	at org.eclipse.core.internal.jobs.JobListeners.waitAndSendEvents(JobListeners.java:78)
	at org.eclipse.core.internal.jobs.JobManager.startJob(JobManager.java:1752)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
```

Indeed currentJob.run is called without waiting for all events to be processed first. If another worker process processes the event the job.eventQueue.isEmpty() check in waitAndSendEvents will be true before the event was processed.

**Comment by iloveeclipse** [comment]
Regression seem to exist since #193, or is this is a regression from #263?

@jukzi : please could you assess the severity of the issue. 

What could be possible regressions from that? 
- Missing events?
- Event sent in wrong order?
- Race conditions in Job framework?

and with that, please assess possible criticality of the proposed patch.

**The main question** for me is: if that should be added to RC2, as a regression in Job framework?

@akurtakov: FYI.

**Comment by akurtakov** [comment]
Do we have an issue for real breakage somewhere? If not I would say this is not for RC2 as the change is in quite critical place.

**Comment by jukzi** [comment]
It could happen is that IJobChangeEvent.running() and Job.run() are executed in parallel. It was never guaranteed in the API that they would not do so. But since the historic implementation did always executed running() before run() there might be clients that relied on that behaviour even though they should not.
I am not aware of any serious bad thing that could happen in the IDE.

**Comment by iloveeclipse** [comment]
Failed again in https://download.eclipse.org/eclipse/downloads/drops4/I20221212-1800/testresults/html/org.eclipse.core.tests.runtime_ep427I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

```
java.lang.AssertionError: Race condition at Event 7 Job.run() in Thread 'Worker-586: testSleepOrderOfEvents'

java.lang.AssertionError: java.lang.AssertionError: Race condition at Event 7 Job.run() in Thread 'Worker-586: testSleepOrderOfEvents'
at org.eclipse.core.tests.runtime.jobs.OrderAsserter.lambda$0(OrderAsserter.java:143)
at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037)
at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054)
at org.eclipse.core.tests.runtime.jobs.OrderAsserter.assertNoErrors(OrderAsserter.java:142)
at org.eclipse.core.tests.runtime.jobs.JobEventTest.testSleepOrderOfEvents(JobEventTest.java:315)
```
