### ISSUE TITLE
Re-scheduling UI job from UI thread can report a deadlock

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#309]
Regression from https://github.com/eclipse-platform/eclipse.platform/issues/193 related changes.

We saw sporadic test fail in our builds using 4.27 M1 that stumbled over this error logged:
```
!ENTRY org.eclipse.core.jobs 4 2 2023-01-09 11:08:30.125
!MESSAGE IJobChangeListener timeout detected. Further calls to IJobChangeListener may occur in random order and join(family) can return too soon. IJobChangeListener should return within 3000 ms. IJobChangeListener methods should not block. Possible deadlock.
!STACK 0
java.util.concurrent.TimeoutException: IJobChangeListener timeout detected. Further calls to IJobChangeListener may occur in random order and join(family) can return too soon. IJobChangeListener should return within 3000 ms. IJobChangeListener methods should not block. Possible deadlock.
	at org.eclipse.core.internal.jobs.JobListeners.waitAndSendEvents(JobListeners.java:97)
	at org.eclipse.core.internal.jobs.JobManager.startJob(JobManager.java:1752)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:228)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)

!SUBENTRY 1 org.eclipse.core.jobs 4 2 2023-01-09 11:08:30.125
!MESSAGE Thread that is running the IJobChangeListener: main
	at org.eclipse.core.internal.jobs.JobManager.withWriteLock(JobManager.java:513)
	at org.eclipse.core.internal.jobs.JobManager.schedule(JobManager.java:1373)
	at org.eclipse.core.internal.jobs.InternalJob.schedule(InternalJob.java:396)
	at org.eclipse.core.runtime.jobs.Job.schedule(Job.java:684)
	at org.eclipse.ui.internal.progress.AnimationManager.setAnimated(AnimationManager.java:122)
	at org.eclipse.ui.internal.progress.AnimationManager$2.decrementJobCount(AnimationManager.java:189)
	at org.eclipse.ui.internal.progress.AnimationManager$2.removeJob(AnimationManager.java:164)
	at org.eclipse.ui.internal.progress.ProgressManager.lambda$11(ProgressManager.java:393)
	at org.eclipse.ui.internal.progress.ProgressManager$$Lambda$919/0x0000000801a67bf0.accept(Unknown Source)
	at java.base@17.0.4/java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.ui.internal.progress.ProgressManager.lambda$10(ProgressManager.java:393)
	at org.eclipse.ui.internal.progress.ProgressManager$$Lambda$378/0x000000080117d000.accept(Unknown Source)
	at java.base@17.0.4/java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:708)
	at org.eclipse.ui.internal.progress.ProgressManager.notifyListeners(ProgressManager.java:393)
	at org.eclipse.ui.internal.progress.ProgressManager$$Lambda$363/0x000000080116d1a0.run(Unknown Source)
	at org.eclipse.jface.util.Throttler.lambda$0(Throttler.java:59)
	at org.eclipse.jface.util.Throttler$$Lambda$364/0x000000080116a7d8.run(Unknown Source)
	at org.eclipse.swt.widgets.Display.timerProc(Display.java:5731)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
...
... unrelated junit test code that has NO relationship to Jobs API
```

Note that there is no `IJobChangeListener` involved at all, it is `JobManager.schedule()` that blocks now, according to the stack, **if** the stack represents the actual blocking code in this case (but it seems to).

In this case it looks like invoking `JobManager.schedule()` to re-schedule UI job from UI thread runs in the same problem like "usual" Job change listeners spending "too much" time on job change events.

**Comment by iloveeclipse** [comment]
The point of this issue is: although there are **no** bad listeners in this case, as a result of the "false positive" check/timeout handling, the Job framework changes behavior at runtime, which may lead again to the **real** issues that the multiple patches for https://github.com/eclipse-platform/eclipse.platform/issues/148 were supposed to fix.

Means: even if the platform / client code doesn't contain any "bad" patterns, it leads to a behavior change and a regression.

Probably the `JobListeners.waitAndSendEvents` needs some extra checks / different way to detect if a bad listener is to blame here (or whatever else), so it would not switch back to "broken" Job framework.

Or UI jobs should be handled differently. Note, that they set **not** the `org.eclipse.core.internal.jobs.Worker` as thread but the "usual" Thread to be able to run UI tasks on SWT main thread. But that is surely not only case where jobs may change thread.

@jukzi : would be good if you could take time to look at this one.

**Comment by jukzi** [comment]
Might be an issue that job.eventQueueThread.set(null) is not in a "finally" clause, or some other thread holding the lock for too long - for unknown reason. Let's dump all threads.
