### ISSUE TITLE
OrderedLockTest randomly fails in different tests

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#316]
Last failures:
- **testComplex** https://download.eclipse.org/eclipse/downloads/drops4/I20230123-1800/testresults/html/org.eclipse.core.tests.runtime_ep427I-unit-cen64-gtk3-java19_linux.gtk.x86_64_19.html
```
testComplex(org.eclipse.core.tests.runtime.jobs.OrderedLockTest): failures 1 out of 10 tries. Last cause:java.lang.IllegalStateException: thread did not end

java.lang.AssertionError: testComplex(org.eclipse.core.tests.runtime.jobs.OrderedLockTest): failures 1 out of 10 tries. Last cause:java.lang.IllegalStateException: thread did not end
at org.eclipse.core.tests.runtime.jobs.RetryTestRule$1.evaluate(RetryTestRule.java:50)

Caused by: java.lang.IllegalStateException: thread did not end
at org.eclipse.core.tests.runtime.jobs.OrderedLockTest.execute(OrderedLockTest.java:302)
at org.eclipse.core.tests.runtime.jobs.OrderedLockTest.lambda$0(OrderedLockTest.java:58)
at org.eclipse.core.internal.jobs.DeadlockDetector.runSilent(DeadlockDetector.java:606)
at org.eclipse.core.tests.runtime.jobs.OrderedLockTest.testComplex(OrderedLockTest.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.eclipse.core.tests.runtime.jobs.RetryTestRule$1.evaluate(RetryTestRule.java:39)
... 62 more
```
- **testSimple** https://download.eclipse.org/eclipse/downloads/drops4/I20230120-1340/testresults/html/org.eclipse.core.tests.runtime_ep427I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
```
testSimple(org.eclipse.core.tests.runtime.jobs.OrderedLockTest): failures 1 out of 10 tries. Last cause:java.lang.IllegalStateException: thread did not end

java.lang.AssertionError: testSimple(org.eclipse.core.tests.runtime.jobs.OrderedLockTest): failures 1 out of 10 tries. Last cause:java.lang.IllegalStateException: thread did not end
at org.eclipse.core.tests.runtime.jobs.RetryTestRule$1.evaluate(RetryTestRule.java:50)

Caused by: java.lang.IllegalStateException: thread did not end
at org.eclipse.core.tests.runtime.jobs.OrderedLockTest.execute(OrderedLockTest.java:302)
at org.eclipse.core.tests.runtime.jobs.OrderedLockTest.lambda$1(OrderedLockTest.java:74)
at org.eclipse.core.internal.jobs.DeadlockDetector.runSilent(DeadlockDetector.java:606)
at org.eclipse.core.tests.runtime.jobs.OrderedLockTest.testSimple(OrderedLockTest.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.eclipse.core.tests.runtime.jobs.RetryTestRule$1.evaluate(RetryTestRule.java:39)
... 64 more
```

See previous (systematic) issue: https://github.com/eclipse-platform/eclipse.platform/issues/145

**Comment by iloveeclipse** [comment]
@jukzi : could you please check?

**Comment by jukzi** [comment]
Impossible to say for me if error is fixed since I can not reproduce it even with RetryTestRule(1000) on my windows
