### ISSUE TITLE
random failing JobTest.testJoinInterruptNonUIThread

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#320]
```
Thread not interrupted expected:<Status CANCEL: unknown code=1 > but was:<Status OK: unknown code=0 OK>
junit.framework.AssertionFailedError: Thread not interrupted expected:<Status CANCEL: unknown code=1 > but was:<Status OK: unknown code=0 OK>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.TestCase.assertEquals(TestCase.java:238)
	at org.eclipse.core.tests.runtime.jobs.JobTest.testJoinInterruptNonUIThread(JobTest.java:1019)
```

in https://github.com/eclipse-platform/eclipse.platform/pull/318/checks?check_run_id=10878070950
and https://github.com/eclipse-platform/eclipse.platform/pull/317#issuecomment-1403299916

**Comment by jukzi** [comment]
can be reproduced with new TestJob("job", **0**, 100);
i.e. probably a timing issue

**Comment by HeikoKlare** [comment]
Test is still failing. See: https://github.com/eclipse-platform/eclipse.platform/actions/runs/4734529994/jobs/8403581311
