### ISSUE TITLE
org.eclipse.ant.tests.ui.BuildTests fails on mac

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform#374]
```
Cannot invoke "org.eclipse.jdt.launching.IVMInstall.getName()" because "vm" is null
java.lang.NullPointerException: Cannot invoke "org.eclipse.jdt.launching.IVMInstall.getName()" because "vm" is null
	at org.eclipse.ant.tests.ui.testplugin.ProjectHelper.setVM(ProjectHelper.java:202)
	at org.eclipse.ant.tests.ui.testplugin.ProjectHelper.createLaunchConfigurationForSeparateVM(ProjectHelper.java:187)
	at org.eclipse.ant.tests.ui.testplugin.ProjectHelper.createLaunchConfigurationForBoth(ProjectHelper.java:163)
	at org.eclipse.ant.tests.ui.testplugin.AbstractAntUITest.assertProject(AbstractAntUITest.java:201)
	at org.eclipse.ant.tests.ui.testplugin.AbstractAntUITest.setUp(AbstractAntUITest.java:149)
	at junit.framework.TestCase.runBare(TestCase.java:140)
	at org.eclipse.ant.tests.ui.testplugin.AbstractAntUITest.runBare(AbstractAntUITest.java:133)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at org.eclipse.ant.tests.ui.AbstractAntUIBuildTest.access$0(AbstractAntUIBuildTest.java:1)
	at org.eclipse.ant.tests.ui.AbstractAntUIBuildTest.lambda$0(AbstractAntUIBuildTest.java:46)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by HeikoKlare** [comment]
Has been fixed with #390.
