### ISSUE TITLE
WeakGroupedListenerList: super slow cleanup / Eclipse process does not terminate after closing all windows

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#375]
Sometimes eclipse.exe does not terminate within reasonable amount of time for minutes. 
Example:

OpenJDK 64-Bit Server VM (17.0.6+10 mixed mode, sharing)
```
"Framework stop - Equinox Container: 8638e99d-ac0d-4962-a6f4-4a2f053ab08e" #6849 prio=6 os_prio=0 cpu=33802,49ms elapsed=34,95s allocated=11658M defined_classes=4 tid=0x00007ff3a0259600 nid=0x5f95 runnable  [0x00007ff3bdd3d000]
   java.lang.Thread.State: RUNNABLE
	at java.util.HashMap$HashIterator.nextNode(java.base@17.0.6/HashMap.java:1601)
	at java.util.HashMap$KeyIterator.next(java.base@17.0.6/HashMap.java:1620)
	at org.eclipse.e4.core.internal.contexts.WeakGroupedListenerList.cleanup(WeakGroupedListenerList.java:130)
	- locked <0x000000069dad6af8> (a org.eclipse.e4.core.internal.contexts.WeakGroupedListenerList)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.cleanup(EclipseContext.java:786)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.cleanup(EclipseContext.java:784)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:208)
	at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:164)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:102)
	at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:144)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:949)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:229)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:138)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:130)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:499)
	at org.eclipse.osgi.container.Module.doStop(Module.java:658)
	at org.eclipse.osgi.container.Module.stop(Module.java:521)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:226)
	at java.lang.Thread.run(java.base@17.0.6/Thread.java:833)

   Locked ownable synchronizers:
	- <0x000000060005ed48> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
```

```
"main" #1 prio=6 os_prio=0 cpu=69499,92ms elapsed=802,98s allocated=3859M defined_classes=13142 tid=0x00007ff5b00269d0 nid=0x35c1 in Object.wait()  [0x00007ff5b5bfd000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.6/Native Method)
	- waiting on <no object reference available>
	at org.eclipse.osgi.container.SystemModule.waitForStop(SystemModule.java:173)
	- locked <0x000000060005edb8> (a java.util.concurrent.atomic.AtomicReference)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle.waitForStop(EquinoxBundle.java:312)
	at org.eclipse.osgi.launch.Equinox.waitForStop(Equinox.java:217)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.shutdown(EclipseStarter.java:458)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:274)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.6/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.6/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.6/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.6/Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```
first observed with eclipse 2022-12.

The same effect of slow WeakGroupedListenerList.cleanup i often see after working a long time with eclipse java ide, which results in 99+ open .java editors. When i then close all editor tabs the UI lags for many seconds in the cleanup. Once i sampled the invocation count i saw millions of calls in that cleanup loop. But i don't know how to reliably reproduce.
The main issue here is that eclipse seems to be closed to the user (There is no option to "cancel"), but the process is still running in background with 100% cpu load. 

workaround: `kill -9`

**Comment by haubi** [comment]
some first profiling session with instrumentation shows interesting call counts:
![image](https://user-images.githubusercontent.com/2249625/227946346-9252f22f-8d91-4340-91ad-446770f3f083.png)

**Comment by haubi** [comment]
It turns out that the trigger for this becoming a problem is some excessive use of `EclipseContextFactory.getServiceContext(...).createChild(...)` by some Eclipse plug-in in some non-static context.

Nevertheless, my impression still is that EclipseContext could do better in handling weak references which's real reference has vanished already, no?

**Comment by jukzi** [comment]
i just noticed that during dispose also new Listener are added - that's probably not what should happen:
```
Thread [Framework stop - Equinox Container: 333ca307-931c-43f3-af49-ba8f0db8c5b1] (Suspended (breakpoint at line 65 in org.eclipse.e4.core.internal.contexts.WeakGroupedListenerList))	
	owns: org.eclipse.e4.core.internal.contexts.WeakGroupedListenerList  (id=877)	
	org.eclipse.e4.core.internal.contexts.WeakGroupedListenerList.add(java.lang.String, org.eclipse.e4.core.internal.contexts.Computation) line: 65	
	org.eclipse.e4.core.internal.contexts.EclipseContext.addDependency(java.lang.String, org.eclipse.e4.core.internal.contexts.Computation) line: 461	
	org.eclipse.e4.core.internal.contexts.EclipseContext.trackAccess(java.lang.String) line: 457	
	org.eclipse.e4.core.internal.contexts.EclipseContext.getLocal(java.lang.String) line: 235	
	org.eclipse.e4.core.internal.contexts.EclipseContext.getLocal(java.lang.Class<T>) line: 606	
	org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(org.eclipse.e4.core.contexts.IEclipseContext, int, java.lang.Object[]) line: 82	
	org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(org.eclipse.e4.core.internal.contexts.ContextChangeEvent) line: 103	
	org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(org.eclipse.e4.core.internal.contexts.ContextChangeEvent, java.util.Set<org.eclipse.e4.core.internal.contexts.EclipseContext.Scheduled>) line: 68	
	org.eclipse.e4.core.internal.contexts.EclipseContext.dispose() line: 179	
	org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi(org.eclipse.e4.core.internal.contexts.EclipseContext).dispose() line: 164	
	org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose() line: 102	
	org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(org.osgi.framework.BundleEvent) line: 144	
	org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(java.lang.Object, java.lang.Object, int, java.lang.Object) line: 949	
	org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(java.util.Set<java.util.Map.Entry<K,V>>, org.eclipse.osgi.framework.eventmgr.EventDispatcher<K,V,E>, int, E) line: 234	
	org.eclipse.osgi.framework.eventmgr.ListenerQueue<K,V,E>.dispatchEventSynchronous(int, E) line: 151	
	org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(org.osgi.framework.BundleEvent) line: 229	
	org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(org.osgi.framework.BundleEvent) line: 138	
	org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(int, org.osgi.framework.Bundle, org.osgi.framework.Bundle) line: 130	
	org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(org.eclipse.osgi.container.ModuleContainerAdaptor$ModuleEvent, org.eclipse.osgi.container.Module, org.eclipse.osgi.container.Module) line: 217	
	org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule(org.eclipse.osgi.container.Module).publishEvent(org.eclipse.osgi.container.ModuleContainerAdaptor$ModuleEvent) line: 499	
	org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule(org.eclipse.osgi.container.Module).doStop() line: 658	
	org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule(org.eclipse.osgi.container.Module).stop(org.eclipse.osgi.container.Module$StopOptions...) line: 521	
	org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule(org.eclipse.osgi.container.SystemModule).stop(org.eclipse.osgi.container.Module$StopOptions...) line: 207	
	org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run() line: 226	
	java.lang.Thread.run() line: 833	

```

**Comment by jukzi** [comment]
While the WeakGroupedListenerList tries to only hold a weak References there is leak for non-disposed Contexts which are injected: There always is a strong reference to the context which is the "key" in InjectorImpl.injectedObjects. That prevents garbage collection.
![image](https://user-images.githubusercontent.com/51790620/228744811-364fa399-f9b4-4e60-8497-0dcd2be6fd57.png)
Only the values of InjectorImpl.injectedObjects are implemented Weak references :-(
