### ISSUE TITLE
Attempted to beginRule: MultiRule[], does not match outer scope rule: R/

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform#376]
I constantly get the following in the log while editing a text file after save.

```
!ENTRY org.eclipse.core.resources 2 75 2023-03-27 12:59:12.255
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.core.resources 2 566 2023-03-27 12:59:12.255
!MESSAGE Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
!STACK 0
java.lang.IllegalArgumentException: Attempted to beginRule: MultiRule[], does not match outer scope rule: R/
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:138)
	at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:402)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:66)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:316)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:240)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:392)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:395)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:506)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:454)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:536)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:196)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:289)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by vogella** [comment]
Which format? I have seen this "only" if I use / install the Asccidoctor Editor Plug-in.

**Comment by laeubi** [comment]
It is a plain text file, no special editor as far as I can see...

**Comment by iloveeclipse** [comment]
It's a custom builder issue.

I assume one of the builders didn't properly implemented overridden `org.eclipse.core.resources.IncrementalProjectBuilder.getRule(int, Map<String, String>)` method and returns an **empty**  `MultiRule` object.

**Comment by laeubi** [comment]
I'm currently experiment with PDE and the project model, as part of this I created a project that only has the PDECLasspathContainer but not a PDE nature (this is intentional as I want to reuse the container outside a "traditional" plugin), it seems most of them use some kind of `MultiRule` and it seems this might can be then an empty array for the multi-rule, but I'm not familiar enough with the rule stuff to tell if it might be wrong implemented ...

**Comment by iloveeclipse** [comment]
OK, this is a regression from https://github.com/eclipse-pde/eclipse.pde/commit/4f2df0738794a698de1f1e2a55255a1848870bf1.

Please create a bug in [PDE](https://github.com/eclipse-pde/eclipse.pde/issues) for that.

**Comment by laeubi** [comment]
Thanks, even though I don't understand the details I opend the issue for PDE now :-)
