### ISSUE TITLE
Marker id ... not found when launching debuggee Eclipse

### ISSUE THREAD

**Issue by trancexpress** [eclipse-platform/eclipse.platform#383]
For some time now. I've occasionally been getting an error dialog and a logged error when launching Eclipse from Eclipse (to debug some problem).

The logged error looks like this:

```
eclipse.buildId=4.28.0.I20230320-1800
java.version=17.0.6
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data /data/workspaces/contributor_workspace

org.eclipse.core.resources
Error
Wed Mar 29 10:32:02 EEST 2023
Marker id 225546 not found.
```

The detailed dialog doesn't show an exception:

```
An exception stack trace is not available.
```

The launch does nothing after the dialog.

**Comment by trancexpress** [comment]
Must be some caller of `Marker.checkInfo(MarkerInfo)` that takes the created `Status` and reports that.

**Comment by trancexpress** [comment]
@iloveeclipse , the merged change should help understand why the launch is prevented by some missing marker. It won't help with it though, there still will be a failed launch (this bug).

**Comment by iloveeclipse** [comment]
Sure, therefore this issue is not closed yet :-)
Once you have a new build, please update this issue with the stack trace and we can see if that can be fixed or not.

**Comment by ewillink** [comment]
> For some time now. 
I upgraded from 4.25 in the hope that this issue would be fixed.

**Comment by trancexpress** [comment]
I got the issue again, now with a stack trace:

```
java.lang.IllegalStateException
	at org.eclipse.core.internal.resources.Marker.checkInfo(Marker.java:63)
	at org.eclipse.core.internal.resources.Marker.getAttribute(Marker.java:108)
	at org.eclipse.debug.core.model.LaunchConfigurationDelegate.isLaunchProblem(LaunchConfigurationDelegate.java:383)
	at org.eclipse.pde.launching.AbstractPDELaunchConfiguration.isLaunchProblem(AbstractPDELaunchConfiguration.java:64)
	at org.eclipse.debug.core.model.LaunchConfigurationDelegate.existsProblems(LaunchConfigurationDelegate.java:364)
	at org.eclipse.debug.core.model.LaunchConfigurationDelegate.finalLaunchCheck(LaunchConfigurationDelegate.java:167)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:792)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:717)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1040)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1243)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

Moving to platform debug.
