### ISSUE TITLE
Random failing org.eclipse.core.tests.internal.builders.BuilderTest.testCopyProject

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#408]
The test `BuilderTest.testCopyProject` randomly fails.
E.g., https://github.com/eclipse-platform/eclipse.platform/pull/352/checks?check_run_id=12610055665
When executed locally and in isolation, the test case always fails on my system.

Test will be fixed when #391 is merged.

```
4.4 expected:<[SetInitializationData, StartupOnInitialize, Build0]> but was:<[SetInitializationData, StartupOnInitialize, Build0, Build0]>
java.lang.AssertionError: 4.4 expected:<[SetInitializationData, StartupOnInitialize, Build0]> but was:<[SetInitializationData, StartupOnInitialize, Build0, Build0]>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.eclipse.core.tests.internal.builders.TestBuilder.assertLifecycleEvents(TestBuilder.java:98)
	at org.eclipse.core.tests.internal.builders.BuilderTest.testCopyProject(BuilderTest.java:751)
```

**Comment by laeubi** [comment]
@HeikoKlare many thanks for taking care about flapping test!
