### ISSUE TITLE
Random failing of IJobManagerTest.testReverseOrder()

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#469]
It happened during [this build](https://github.com/eclipse-platform/eclipse.platform/actions/runs/4988938481/jobs/8932229100#step:7:11196) of the PR #443 

```org.eclipse.core.tests.runtime.jobs.IJobManagerTest.testReverseOrder  Time elapsed: 0.721 s  <<< FAILURE!
junit.framework.AssertionFailedError: 1.1.0 expected:<testReverseOrder(0)(587)> but was:<testReverseOrder(1)(588)>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.TestCase.assertEquals(TestCase.java:238)
	at org.eclipse.core.tests.runtime.jobs.IJobManagerTest.testReverseOrder(IJobManagerTest.java:1778)
```

**Comment by fedejeanne** [comment]
Please observe: this happened after merging #401 so there might be some other issue with the tests in `IJobManagerTest`
