### ISSUE TITLE
platform SDK install fails

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform#47]
I try to setup a fresh SDK install because my old one is wrecked, now I get the following error:

```
ERROR: org.eclipse.pde.core code=0 Problems occurred while resolving the target contents
  at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:296)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.activateTargetDefinition(TargetPlatformUtil.java:151)
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:905)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1232)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1092)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3864)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5200)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5193)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3798)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3773)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3651)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:592)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:721)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
    ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1657945607175
    ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Equinox p2, headless functionalities 1.6.1500.v20220710-1223 (org.eclipse.equinox.p2.core.feature.feature.group 1.6.1500.v20220710-1223) requires 'org.eclipse.equinox.p2.iu; bcpg 0.0.0' but it could not be found
    ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
      ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1657945607175
      ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.equinox.p2.core.feature.feature.group 0.0.0
```

**Comment by laeubi** [comment]
@mickaelistria maybe because the recent changes of artifact migration, need the setup be adjusted as well?

**Comment by merks** [comment]
I looks like it's simply because these changes from yesterday did not made it into a nightly build yet:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/403/files#diff-8882811e0de1dbbb6fe45ff8d54c77dab3ca39219d958783ad4f3779cdc1a4e8R263
https://github.com/eclipse-equinox/p2/commit/b1dd89f6bd58aa14448f6c780e7b3d9207912e0d

This is the newest I see this moment, and it still contains the Orbit bcpg:

https://download.eclipse.org/justj/?file=eclipse/updates/4.25-I-builds/I20220715-1800/plugins

![image](https://user-images.githubusercontent.com/208716/179341013-9e133c9a-c915-43ce-a57b-2a6e828fc446.png)

The problem should fix itself with the next promoted I-Build.

**Comment by laeubi** [comment]
Thanks Ed, have a nice weekend :+1:
