### ISSUE TITLE
ant.tests.ui hang in I20230620-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#511]
See 
- https://download.eclipse.org/eclipse/downloads/drops4/I20230620-1800/testResults.php
- https://download.eclipse.org/eclipse/downloads/drops4/I20230620-1800/logs.php#console
- https://download.eclipse.org/eclipse/downloads/drops4/I20230620-1800/testresults/ep429I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20/org.eclipse.ant.tests.ui.testplugin.AntUITests.txt [org.eclipse.ant.tests.ui.testplugin.AntUITests.txt](https://github.com/eclipse-platform/eclipse.platform/files/11817057/org.eclipse.ant.tests.ui.testplugin.AntUITests.txt)

Ant bundle code hangs because ant hangs forever reading input (no idea why) in a synchronized block, which also guards shutdown code

**Thread that waits for input and locked RemoteAntBuildListener object**
```
java.lang.Exception: ThreadDump for thread "Ant Request Response Reader Thread"
	at java.base@20/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base@20/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:47)
	at java.base@20/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:251)
	at java.base@20/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:302)
	at java.base@20/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:340)
	at java.base@20/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:789)
	at java.base@20/java.net.Socket$SocketInputStream.read(Socket.java:1025)
	at java.base@20/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:333)
	at java.base@20/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:376)
	at java.base@20/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:219)
	at java.base@20/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:173)
	at java.base@20/java.io.InputStreamReader.read(InputStreamReader.java:189)
	at java.base@20/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base@20/java.io.BufferedReader.implReadLine(BufferedReader.java:371)
	at java.base@20/java.io.BufferedReader.readLine(BufferedReader.java:348)
	at java.base@20/java.io.BufferedReader.readLine(BufferedReader.java:437)
	at org.eclipse.ant.internal.launching.debug.model.RemoteAntDebugBuildListener$ReaderThread.run(RemoteAntDebugBuildListener.java:63)
```

**Shutdown thread waits for lock on RemoteAntBuildListener object**
```
java.lang.Exception: ThreadDump for thread "Ant Build Server Connection"
	at org.eclipse.ant.internal.launching.debug.model.RemoteAntDebugBuildListener.shutDown(RemoteAntDebugBuildListener.java:210)
	at org.eclipse.ant.internal.launching.launchConfigurations.RemoteAntBuildListener$ServerConnection.run(RemoteAntBuildListener.java:109)
```

**SteppingTests.testStepOutOfMacrodefSepVM waits for lock on RemoteAntBuildListener object**
```
java.lang.Exception: ThreadDump for thread "Thread-104"
	at org.eclipse.ant.internal.launching.debug.model.RemoteAntDebugBuildListener.shutDown(RemoteAntDebugBuildListener.java:210)
	at org.eclipse.ant.internal.launching.launchConfigurations.RemoteAntBuildListener.launchesRemoved(RemoteAntBuildListener.java:386)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchesNotifier.run(LaunchManager.java:275)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchesNotifier.notify(LaunchManager.java:261)
	at org.eclipse.debug.internal.core.LaunchManager.fireUpdate(LaunchManager.java:1056)
	at org.eclipse.debug.internal.core.LaunchManager.removeLaunch(LaunchManager.java:2209)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationManager.removeTerminatedLaunches(LaunchConfigurationManager.java:327)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationManager.launchAdded(LaunchConfigurationManager.java:315)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchNotifier.run(LaunchManager.java:424)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.debug.internal.core.LaunchManager$LaunchNotifier.notify(LaunchManager.java:414)
	at org.eclipse.debug.internal.core.LaunchManager.fireUpdate(LaunchManager.java:1045)
	at org.eclipse.debug.internal.core.LaunchManager.addLaunch(LaunchManager.java:692)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:763)
	at org.eclipse.ant.tests.ui.debug.AbstractAntDebugTest.launchAndWait(AbstractAntDebugTest.java:173)
	at org.eclipse.ant.tests.ui.debug.AbstractAntDebugTest.launchAndWait(AbstractAntDebugTest.java:155)
	at org.eclipse.ant.tests.ui.debug.AbstractAntDebugTest.launchToLineBreakpoint(AbstractAntDebugTest.java:369)
	at org.eclipse.ant.tests.ui.debug.SteppingTests.debugStack(SteppingTests.java:128)
	at org.eclipse.ant.tests.ui.debug.SteppingTests.testStepOutOfMacrodefSepVM(SteppingTests.java:189)
```

**Comment by jukzi** [comment]
can you reproduce it locally? i can't

**Comment by iloveeclipse** [comment]
> can you reproduce it locally? i can't

I haven't tried. Note, if you've tried, you may need to use Java 20 + entire testsuite, may be some test before didn't properly clean up.

**Comment by jukzi** [comment]
AntUITests with 20 on win do not hang, but produce 47/229 failures

**Comment by iloveeclipse** [comment]
> I haven't tried

Now I've tried. What is interesting, I see no fails on Java 17 nad ~40 various test fails on Java 20. 
Where are the fails on official build???

**Comment by jukzi** [comment]
And why do they fail on 20? I compared the console output of a failing test with it's 17 and see no differences except other jdk stacktraces and dates. Both expected.

**Comment by iloveeclipse** [comment]
> And why do they fail on 20

I assume one of the JDK "cleanup" actions like removing SecurityManager breaks ant. I assume the tests run with extra arguments to avoid that fails.
