### ISSUE TITLE
Possibly leaking Timer instances?

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#538]
See https://github.com/eclipse-jdt/eclipse.jdt.debug/issues/137

The stack there shows an immense number of waiting TimerTreads, which could be a problem if there are not enough threads to schedule new jobs.

```
java.lang.Exception: ThreadDump for thread "Timer-983"
	at java.base@18.0.1.1/java.lang.Object.wait(Native Method)
	at java.base@18.0.1.1/java.lang.Object.wait(Object.java:338)
	at java.base@18.0.1.1/java.util.TimerThread.mainLoop(Timer.java:537)
	at java.base@18.0.1.1/java.util.TimerThread.run(Timer.java:516)
```

On a quick look, we **might** leak `org.eclipse.debug.internal.ui.viewers.update.EventHandlerModelProxy.fTimer` object by not always disposing `EventHandlerModelProxy` subclass instances, but I haven't verified that.

**Comment by jukzi** [comment]
closing, seems to be irrelevant after 2 years
