### ISSUE TITLE
Random failing LaunchConfigurationTests.testTerminateTimeStamp

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#582]
`org.eclipse.debug.tests.launching.LaunchConfigurationTests.testTerminateTimeStamp` randomly fails, e.g. https://github.com/eclipse-platform/eclipse.platform/actions/runs/5622957268/job/15236595341

```
org.eclipse.debug.tests.launching.LaunchConfigurationTests.testTerminateTimeStamp -- Time elapsed: 30.05 s <<< FAILURE!
java.lang.AssertionError: Launch did not finished
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.debug.tests.TestUtil.waitWhile(TestUtil.java:138)
	at org.eclipse.debug.tests.AbstractDebugTest.waitWhile(AbstractDebugTest.java:116)
	at org.eclipse.debug.tests.launching.LaunchConfigurationTests.testTerminateTimeStamp(LaunchConfigurationTests.java:1371)
```

The implementation launches a configuration before registering the listener that waits for its termination. This induces a race condition that might be the reason for the failing test.

**Comment by jukzi** [comment]
https://github.com/eclipse-platform/eclipse.platform/actions/runs/5657225255/job/15326634462

```
Launch did not finish
java.lang.AssertionError: Launch did not finish
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.debug.tests.TestUtil.waitWhile(TestUtil.java:138)
	at org.eclipse.debug.tests.AbstractDebugTest.waitWhile(AbstractDebugTest.java:116)
	at org.eclipse.debug.tests.launching.LaunchConfigurationTests.testTerminateTimeStamp(LaunchConfigurationTests.java:1366)

```

**Comment by HeikoKlare** [comment]
Log shows that process has actually terminated but termination event was not processed by listener.

```
Launch termination event did not occur and termination state of launched process is: true
java.lang.AssertionError: Launch termination event did not occur and termination state of launched process is: true
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.debug.tests.TestUtil.waitWhile(TestUtil.java:138)
	at org.eclipse.debug.tests.AbstractDebugTest.waitWhile(AbstractDebugTest.java:116)
	at org.eclipse.debug.tests.launching.LaunchConfigurationTests.testTerminateTimeStamp(LaunchConfigurationTests.java:1367)
```

**Comment by fedejeanne** [comment]
It failed again in [this build](https://github.com/eclipse-platform/eclipse.platform/pull/591/checks?check_run_id=15331977026) of https://github.com/eclipse-platform/eclipse.platform/pull/591 with the same stack trace:
```
Launch termination event did not occur and termination state of launched process is: true
java.lang.AssertionError: Launch termination event did not occur and termination state of launched process is: true
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.debug.tests.TestUtil.waitWhile(TestUtil.java:138)
	at org.eclipse.debug.tests.AbstractDebugTest.waitWhile(AbstractDebugTest.java:116)
	at org.eclipse.debug.tests.launching.LaunchConfigurationTests.testTerminateTimeStamp(LaunchConfigurationTests.java:1367)
...
```

**Comment by HeikoKlare** [comment]
(Likely) reason for the random test failure is documented in separate issue #598, as it is not only a test bug but one in productive code.
