### ISSUE TITLE
Random failing org.eclipse.core.tests.resources.CharsetTest.testDeltasContainer 

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#584]
The test case `org.eclipse.core.tests.resources.CharsetTest.testDeltasContainer` randomly fails, e.g.  https://github.com/eclipse-platform/eclipse.platform/pull/583/checks?check_run_id=15291909544

```
Verifier has not yet been given a resource delta
java.lang.AssertionError: Verifier has not yet been given a resource delta
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.core.tests.resources.ResourceDeltaVerifier.isDeltaValid(ResourceDeltaVerifier.java:536)
	at org.eclipse.core.tests.resources.CharsetTest$MultipleDeltasCharsetVerifier.assertExpectedDeltasWereReceived(CharsetTest.java:1508)
	at org.eclipse.core.tests.resources.CharsetTest.testDeltasContainer(CharsetTest.java:1136)
```

The issue of a `ResourceVerifier` not being notified about changes has already been an issue with other related test cases:
* #99 
* #319

**Comment by HeikoKlare** [comment]
Didn't see this failure for a long time. Test still exists and seems to work just fine.
