### ISSUE TITLE
Random failing InputStreamMonitorTests.testInputStreamMonitor

### ISSUE THREAD

**Issue by Michael5601** [eclipse-platform/eclipse.platform#629]
The test case `org.eclipse.debug.tests.console.InputStreamMonitorTests.testInputStreamMonitor` randomly fails:
```java
Monitor wrote to few bytes. expected:<50> but was:<100>
java.lang.AssertionError: Monitor wrote to few bytes. expected:<50> but was:<100>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.eclipse.debug.tests.console.InputStreamMonitorTests.testInputStreamMonitor(InputStreamMonitorTests.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
```
Locally this test does not fail with my setup. But in PR https://github.com/eclipse-platform/eclipse.platform/pull/618 it failed even though my changes don't change anything related.

**Comment by HeikoKlare** [comment]
Should have been fixed by #835.
