### ISSUE TITLE
Problem during initializing system proxy configuration

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#636]
Using I20230811-1800.
Seem to be a recent regression on Windows, I do not see this with I20230806-1800.
I see this reported on startup in the error log, never seen this before:
```
eclipse.buildId=4.29.0.I20230811-1800
java.version=17.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data file:/D:/tmp/wsp/

org.eclipse.core.net
Error
Sat Aug 12 09:22:41 CEST 2023
Problem during initializing system proxy configuration.

java.lang.UnsatisfiedLinkError: C:\tmp\jna-1965574031\jna5770391313535858875.dll: %1 ist keine zulässige Win32-Anwendung
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1045)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015)
	at com.sun.jna.Native.<clinit>(Native.java:221)
	at org.eclipse.core.net.ProxyProvider.<clinit>(ProxyProvider.java:70)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at org.eclipse.core.internal.net.ProxyManager.<init>(ProxyManager.java:65)
	at org.eclipse.core.internal.net.ProxyManager.getProxyManager(ProxyManager.java:81)
	at org.eclipse.core.internal.net.Activator.start(Activator.java:176)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1032)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:371)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.framework.util.SecureAction.start(SecureAction.java:513)
	at org.eclipse.osgi.internal.hooks.EclipseLazyStarter.postFindLocalClass(EclipseLazyStarter.java:117)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:570)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:335)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:397)
	at org.eclipse.osgi.internal.loader.sources.SingleSourcePackage.loadClass(SingleSourcePackage.java:41)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:496)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.activateProxyService(IDEWorkbenchAdvisor.java:298)
	at org.eclipse.ui.internal.ide.application.IDEWorkbenchAdvisor.postStartup(IDEWorkbenchAdvisor.java:276)
	at org.eclipse.ui.internal.Workbench.lambda$17(Workbench.java:2844)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1112)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```

**Comment by iloveeclipse** [comment]
OK, I see that after installing jgit to the platform. 
That seem to pull in `5.13.0.v20230807-0900` of `com.sun.jna` library from https://download.eclipse.org/tools/orbit/downloads/latest-I, which causes trouble. 
SDK contains `5.13.0` version which works fine.

@merks : is this something that also requires Orbit fix?

**Comment by merks** [comment]
The orbit version signs both the *.dll and the *.jnilib.

https://github.com/eclipse-orbit/orbit-simrel/issues/7

But this makes is sound like maybe the *.dll signing corrupted the library.  I could disable the *.dll signing, but it "should just work".

**Comment by iloveeclipse** [comment]
I've also noticed, the orbit version is installed as a directory, while SDK version is plain jar. Does it make a difference may be?

**Comment by merks** [comment]
It should not make a difference, at least not in principle.  But I also didn't do anything explicitly so that would be the case.

**Comment by iloveeclipse** [comment]
OK, so what do we need to do now to fix this? Is there a way one can avoid getting updated / broken jna library?

**Comment by merks** [comment]
Note that I only have two hands.  😱

**Comment by iloveeclipse** [comment]
Sure, qnd we have a weekend too. I just want to know if there is an idea of a solution or workaround available.

**Comment by merks** [comment]
Yes, I will just disable the signing of *.dll, assuming that is the problem.  The feature.xml says unpack false so I don't expect it to be unpacked so the jar itself should be installed as a jar.

    <plugin id="com.sun.jna" unpack="false" version="5.13.0"/>

Your error message suggests the *.dll is extracted to a tmp folder but that doesn't make sense either, i.e., isn't something I expect OSGi to do.  It does need to extract the library from the jar if the library is in a jar, so maybe it does that to a temp folder first...

**Comment by laeubi** [comment]
>  The feature.xml says unpack false 

Pleas note that whatever the feature.xml says is completely useless and actually the [`Eclipse-BundleShape`](https://eclipsesource.com/blogs/2009/01/20/tip-eclipse-bundleshape/) controls if a bundle is exploded or not ...

**Comment by merks** [comment]
I checked that too, and that's not present.   We reuse exactly what's available here:

https://repo1.maven.org/maven2/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar

We just open the jar, sign the libraries, and repackage.

In any case, there is a new version where the *.dll is not signed:

![image](https://github.com/eclipse-platform/eclipse.platform/assets/208716/6a612c79-4462-44cb-ba21-8e0171258cb0)

**Comment by iloveeclipse** [comment]
Thanks! That fixed the problem for me!

**Comment by merks** [comment]
Thanks for the quick turn around!  🥇

**Comment by iloveeclipse** [comment]
Hmm.. See https://ci.eclipse.org/releng/job/Builds/job/I-build-4.29/101/console
```
15:10:54  [ERROR] Cannot resolve project dependencies:
15:10:54  [ERROR]   Software being installed: org.eclipse.sdk.ide 4.29.0.qualifier
15:10:54  [ERROR]   Missing requirement: org.eclipse.sdk.feature.group 4.29.0.v20230812-0953 requires 'org.eclipse.equinox.p2.iu; org.eclipse.platform.feature.group [4.29.0.v20230812-0600,4.29.0.v20230812-0600]' but it could not be found
15:10:54  [ERROR]   Cannot satisfy dependency: org.eclipse.sdk.ide 4.29.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.sdk.feature.group 0.0.0
```

???

**Comment by HannesWell** [comment]
I encountered this with the latest staging EPP DSL package for M2. Thanks for fixing this.

> > The feature.xml says unpack false
> 
> Pleas note that whatever the feature.xml says is completely irrelevant and actually the [`Eclipse-BundleShape`](https://eclipsesource.com/blogs/2009/01/20/tip-eclipse-bundleshape/) controls if a bundle is exploded or not ...

I think we should stop generating those attributes in PDE.
