### ISSUE TITLE
Unknown extension point: 'org.eclipse.core.tests.harness.tests'

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#638]
With a fresh Oomphed Eclipse IDE i get this error. I have not seen it before.

```
Description	Resource	Path	Location	Type
Unknown extension point: 'org.eclipse.core.tests.harness.tests'	plugin.xml	/org.eclipse.core.tests.resources.saveparticipant	line 5	Plug-in Problem
```
![image](https://github.com/eclipse-platform/eclipse.platform/assets/51790620/307931bb-d322-4d20-bfb4-58ece4d9dc14)

It's used here, but i don't find where it is defined
https://github.com/eclipse-platform/eclipse.platform/blob/master/resources/tests/org.eclipse.core.tests.resources.saveparticipant/plugin.xml

**Comment by jukzi** [comment]
The only way to start those SaveManagerTest i found was to manually start org.eclipse.core.tests.resources.session.SaveParticipantTest.
When i do that test3 fails

```
junit.framework.AssertionFailedError: 6.0
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:223)
	at org.eclipse.core.tests.resources.saveparticipant.SaveManager3Test.testSaveParticipant(SaveManager3Test.java:143)
	at org.eclipse.core.tests.resources.saveparticipant.SaveManagerTest.test3(SaveManagerTest.java:104)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:128)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.pde.internal.junit.runtime.RemotePluginTestRunner.main(RemotePluginTestRunner.java:81)
	at org.eclipse.pde.internal.junit.runtime.CoreTestApplication.start(CoreTestApplication.java:28)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
	at org.eclipse.core.launcher.Main.main(Main.java:44)
```

logging

```
!MESSAGE [test3] setUp
delta is different than expected
Verifying delta for /
Verifying delta for /MyProject
Verifying delta for /MyProject/addedFile
Verifying delta for /Project2
Verifying delta for /Project2/.project
Verifying delta for /Project2/.settings
	Missing expected change
		Actual kind: <ADDED>
		Actual change flags: <0>
Verifying delta for /Project2/.settings/org.eclipse.core.resources.prefs
	Missing expected change
		Actual kind: <ADDED>
		Actual change flags: <0>
Verifying delta for /Project2/addedFile
Verifying delta for /Project2/file110
Verifying delta for /Project2/folder110
Verifying delta for /Project2/folder110/file120
Verifying delta for /Project2/folder111
Verifying delta for /Project2/folder111/file121
Verifying delta for /Project2/folder111/folder120
```

**Comment by jukzi** [comment]
the extension point was deleted almost 20 years ago with https://github.com/eclipse-platform/eclipse.platform/commit/b45ea6adae665e194140b7508df96794a084bee7.patch

**Comment by jukzi** [comment]
the Class EclipseTestHarnessApplication that used the extension point was recently deleted with https://github.com/eclipse-platform/eclipse.platform/commit/88dce1424bf72b4da041ef11c7b8c58aa8248fcf
