### ISSUE TITLE
Various startup problems linked to IllegalStateException: Workspace is already closed or not ready yet

### ISSUE THREAD

**Issue by rombert** [eclipse-platform/eclipse.platform#644]
My Eclipse 2023-06 has various startup problems - CNFE, unable to initialise plug-in, etc, and looking at the error log I see that the root cause _seems to be_ in org.eclipse.debug.core

```
java.lang.IllegalStateException: Workspace is already closed or not ready yet. Consider tracking the org.eclipse.core.resources.IWorkspace service (using your favorite technique, e.g. Declarative Services, ServiceTracker, Blueprint, ...) instead of calling the static method here to prevent such issues!
	at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:502)
	at org.eclipse.debug.core.DebugPlugin.start(DebugPlugin.java:731)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:818)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$2.run(BundleContextImpl.java:1)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:810)
```

The version of the debug.core plugin is 
> Eclipse.org	Debug Core	3.21.0.v20230508-1538	org.eclipse.debug.core

I've attached the full stack trace, in case it helps: [stack_trace_eclipse.txt](https://github.com/eclipse-platform/eclipse.platform/files/12418537/stack_trace_eclipse.txt)

I'm happy to provide more information, but I am not sure what exactly is useful right now.

**Comment by rombert** [comment]
Haven't tried a fresh installation yet. But when I can tell you is that it does not happen if I restart Eclipse via File → Restart, but it does happen when I started it cleanly.

It happen of a fresh start of my 'legacy' workspace with lots of projects and configs, but also on a relatively clean workspace with just three small m2e/Java projects.

**Comment by rombert** [comment]
Closing as this does not reproduce after upgrading to Eclipse 2023-09 RC1.
