### ISSUE TITLE
core.tests.resources DNF in I20230823-0600

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#645]
See 
- https://download.eclipse.org/eclipse/downloads/drops4/I20230823-0600/testResults.php
- https://download.eclipse.org/eclipse/downloads/drops4/I20230823-0600/logs.php#console
- https://download.eclipse.org/eclipse/downloads/drops4/I20230823-0600/testresults/ep429I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20/org.eclipse.core.tests.resources.AutomatedResourceTests.txt

The first hang dump is :  
```
!ENTRY org.eclipse.core.tests.resources 1 0 2023-08-23 14:10:13.099
!MESSAGE [test1] setUp
!SESSION 2023-08-23 14:10:14.024 -----------------------------------------------
eclipse.buildId=4.29.0.I20230823-0600
java.version=20
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -test org.eclipse.core.tests.resources.session.TestClosedProjectLocation:test2 -testpluginname org.eclipse.core.tests.resources -version 3 -application org.eclipse.pde.junit.runtime.coretestapplication -port 40633
Command-line arguments:  -data /home/jenkins/agent/workspace/AutomatedTests/ep429I-unit-cen64-gtk3-java20/tmp/69301718300 -os linux -test org.eclipse.core.tests.resources.session.TestClosedProjectLocation:test2 -testpluginname org.eclipse.core.tests.resources -version 3 -application org.eclipse.pde.junit.runtime.coretestapplication -port 40633 -arch x86_64 -ws gtk

!ENTRY org.eclipse.core.tests.resources 1 0 2023-08-23 14:10:20.086
!MESSAGE [test2] setUp
DumpStackTracesTimer almost reached timeout '7200000'.
totalMemory:            1920806912
freeMemory (before GC): 1811201616
freeMemory (after GC):  1253660688
Thread dump 0 at 2023-08-23 16:00:34 +0000:
java.lang.Exception: ThreadDump for thread "Worker-47"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
java.lang.Exception: ThreadDump for thread "Common-Cleaner"
	at java.base@20/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@20/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
	at java.base@20/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1847)
	at java.base@20/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:71)
	at java.base@20/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:143)
	at java.base@20/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:218)
	at java.base@20/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
	at java.base@20/java.lang.Thread.runWith(Thread.java:1636)
	at java.base@20/java.lang.Thread.run(Thread.java:1623)
	at java.base@20/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
java.lang.Exception: ThreadDump for thread "Java indexing"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at java.base@20/java.lang.Object.wait(Object.java:339)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:488)
	at org.eclipse.jdt.internal.core.search.processing.JobManager$$Lambda$572/0x0000000801408ee0.run(Unknown Source)
	at java.base@20/java.lang.Thread.runWith(Thread.java:1636)
	at java.base@20/java.lang.Thread.run(Thread.java:1623)
java.lang.Exception: ThreadDump for thread "EMF Reference Cleaner"
	at java.base@20/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@20/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
	at java.base@20/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
	at java.base@20/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
	at java.base@20/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
	at java.base@20/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
	at java.base@20/java.lang.ref.ReferenceQueue.await(ReferenceQueue.java:67)
	at java.base@20/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
	at java.base@20/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:234)
	at org.eclipse.emf.common.util.CommonUtil$1ReferenceClearingQueuePollingThread.run(CommonUtil.java:70)
java.lang.Exception: ThreadDump for thread "process reaper (pid 82488)"
	at java.base@20/java.lang.ProcessHandleImpl.waitForProcessExit0(Native Method)
	at java.base@20/java.lang.ProcessHandleImpl$1.run(ProcessHandleImpl.java:163)
	at java.base@20/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base@20/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@20/java.lang.Thread.runWith(Thread.java:1636)
	at java.base@20/java.lang.Thread.run(Thread.java:1623)
	at java.base@20/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:186)
java.lang.Exception: ThreadDump for thread "Notification Thread"
java.lang.Exception: ThreadDump for thread "main"
	at java.base@20/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@20/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
	at java.base@20/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
	at java.base@20/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
	at java.base@20/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
	at java.base@20/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
	at java.base@20/java.lang.ProcessImpl.waitFor(ProcessImpl.java:447)
	at org.eclipse.core.tests.session.ProcessController.execute(ProcessController.java:115)
	at org.eclipse.core.tests.session.Setup.run(Setup.java:405)
	at org.eclipse.core.tests.session.SessionTestRunner.launch(SessionTestRunner.java:262)
	at org.eclipse.core.tests.session.SessionTestRunner.run(SessionTestRunner.java:291)
	at org.eclipse.core.tests.session.TestDescriptor.run(TestDescriptor.java:95)
	at org.eclipse.core.tests.session.SessionTestSuite.runSessionTest(SessionTestSuite.java:169)
	at org.eclipse.core.tests.session.SessionTestSuite.runTest(SessionTestSuite.java:190)
	at org.eclipse.core.tests.session.WorkspaceSessionTestSuite.run(WorkspaceSessionTestSuite.java:74)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:198)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:169)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:93)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:58)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator$$Lambda$394/0x0000000801349dd0.accept(Unknown Source)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:141)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:57)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:103)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
	at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:63)
	at org.eclipse.test.EclipseTestRunner.runTests(EclipseTestRunner.java:212)
	at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:187)
	at org.eclipse.test.CoreTestApplication.runTests(CoreTestApplication.java:53)
	at org.eclipse.test.CoreTestApplication.run(CoreTestApplication.java:35)
	at org.eclipse.test.CoreTestApplication.start(CoreTestApplication.java:44)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base@20/java.lang.invoke.DirectMethodHandle$Holder.invokeStatic(DirectMethodHandle$Holder)
	at java.base@20/java.lang.invoke.LambdaForm$MH/0x0000000801006800.invoke(LambdaForm$MH)
	at java.base@20/java.lang.invoke.LambdaForm$MH/0x0000000801006c00.invokeExact_MT(LambdaForm$MH)
	at java.base@20/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:156)
	at java.base@20/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base@20/java.lang.reflect.Method.invoke(Method.java:578)
	at app//org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at app//org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at app//org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at app//org.eclipse.equinox.launcher.Main.main(Main.java:1432)
	at app//org.eclipse.core.launcher.Main.main(Main.java:44)
java.lang.Exception: ThreadDump for thread "Finalizer"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at java.base@20/java.lang.Object.wait(Object.java:339)
	at java.base@20/java.lang.ref.NativeReferenceQueue.await(NativeReferenceQueue.java:48)
	at java.base@20/java.lang.ref.ReferenceQueue.remove0(ReferenceQueue.java:158)
	at java.base@20/java.lang.ref.NativeReferenceQueue.remove(NativeReferenceQueue.java:89)
	at java.base@20/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:173)
java.lang.Exception: ThreadDump for thread "Worker-JM"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at org.eclipse.core.internal.jobs.InternalWorker.run(InternalWorker.java:61)
java.lang.Exception: ThreadDump for thread "Active Thread: Equinox Container: b2c75b8d-6749-4d8a-9e98-da25eca6a5ab"
	at java.base@20/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@20/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:269)
	at java.base@20/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1758)
	at java.base@20/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1182)
	at java.base@20/java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:899)
	at java.base@20/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
	at java.base@20/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@20/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@20/java.lang.Thread.runWith(Thread.java:1636)
	at java.base@20/java.lang.Thread.run(Thread.java:1623)
java.lang.Exception: ThreadDump for thread "DumpStackTracesTimer"
	at java.base@20/java.lang.Thread.dumpThreads(Native Method)
	at java.base@20/java.lang.Thread.getAllStackTraces(Thread.java:2585)
	at org.eclipse.ui.testing.dumps.TimeoutDumpTimer.dumpStackTraces(TimeoutDumpTimer.java:237)
	at org.eclipse.ui.testing.dumps.TimeoutDumpTimer.dump(TimeoutDumpTimer.java:158)
	at org.eclipse.ui.testing.dumps.TimeoutDumpTimer.run(TimeoutDumpTimer.java:131)
	at java.base@20/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base@20/java.util.TimerThread.run(Timer.java:516)
java.lang.Exception: ThreadDump for thread "Signal Dispatcher"
java.lang.Exception: ThreadDump for thread "Stream forwarder [stdout]"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at org.eclipse.core.tests.session.ProcessController$2.run(ProcessController.java:156)
java.lang.Exception: ThreadDump for thread "SCR Component Actor"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at java.base@20/java.lang.Object.wait(Object.java:339)
	at org.apache.felix.scr.impl.ComponentActorThread.run(ComponentActorThread.java:83)
	at java.base@20/java.lang.Thread.runWith(Thread.java:1636)
	at java.base@20/java.lang.Thread.run(Thread.java:1623)
java.lang.Exception: ThreadDump for thread "Gogo shell"
	at java.base@20/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@20/java.util.concurrent.locks.LockSupport.park(LockSupport.java:371)
	at java.base@20/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:519)
	at java.base@20/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3780)
	at java.base@20/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3725)
	at java.base@20/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1707)
	at java.base@20/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
	at java.base@20/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1070)
	at java.base@20/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base@20/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base@20/java.lang.Thread.runWith(Thread.java:1636)
	at java.base@20/java.lang.Thread.run(Thread.java:1623)
java.lang.Exception: ThreadDump for thread "Reference Handler"
	at java.base@20/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
	at java.base@20/java.lang.ref.Reference.processPendingReferences(Reference.java:246)
	at java.base@20/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:208)
java.lang.Exception: ThreadDump for thread "Provisioning Event Dispatcher"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at java.base@20/java.lang.Object.wait(Object.java:339)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
java.lang.Exception: ThreadDump for thread "Refresh Thread: Equinox Container: b2c75b8d-6749-4d8a-9e98-da25eca6a5ab"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at java.base@20/java.lang.Object.wait(Object.java:339)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
java.lang.Exception: ThreadDump for thread "Stream forwarder [stderr]"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at org.eclipse.core.tests.session.ProcessController$2.run(ProcessController.java:156)
java.lang.Exception: ThreadDump for thread "Test result collector"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at org.eclipse.core.tests.session.SessionTestRunner$ResultCollector.run(SessionTestRunner.java:195)
	at java.base@20/java.lang.Thread.runWith(Thread.java:1636)
	at java.base@20/java.lang.Thread.run(Thread.java:1623)
java.lang.Exception: ThreadDump for thread "Worker-49"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
java.lang.Exception: ThreadDump for thread "Start Level: Equinox Container: b2c75b8d-6749-4d8a-9e98-da25eca6a5ab"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at java.base@20/java.lang.Object.wait(Object.java:339)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
java.lang.Exception: ThreadDump for thread "Worker-45"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
	at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
java.lang.Exception: ThreadDump for thread "Framework Event Dispatcher: Equinox Container: b2c75b8d-6749-4d8a-9e98-da25eca6a5ab"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at java.base@20/java.lang.Object.wait(Object.java:339)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
java.lang.Exception: ThreadDump for thread "Bundle File Closer"
	at java.base@20/java.lang.Object.wait0(Native Method)
	at java.base@20/java.lang.Object.wait(Object.java:366)
	at java.base@20/java.lang.Object.wait(Object.java:339)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.getNextEvent(EventManager.java:400)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:341)
```

**Comment by iloveeclipse** [comment]
One thing that strikes me immediately: since when do we have **JDT** code / bundles during our resources tests???
I would not expect java indexer running, but it is obviously there: `org.eclipse.jdt.internal.core.search.processing.JobManager.indexerLoop(JobManager.java:488)`

**Comment by mickaelistria** [comment]
> One thing that strikes me immediately: since when do we have JDT code / bundles during our resources tests???

Unlike Tycho which uses only the dependencies, isn't the Eclipse Tester actually running the tests in the whole SDK (so JDT's contributions to CNF are present in that case) ?

**Comment by akurtakov** [comment]
> > One thing that strikes me immediately: since when do we have JDT code / bundles during our resources tests???
> 
> Unlike Tycho which uses only the dependencies, isn't the Eclipse Tester actually running the tests in the whole SDK (so JDT's contributions to CNF are present in that case) ?

I think that's exactly it.

**Comment by iloveeclipse** [comment]
Hmm. I don't see anything in the stack that could give a hint why don't we move forward with the test. Could be the thread dump is (consistently) incomplete, I see no stack for
```
java.lang.Exception: ThreadDump for thread "Notification Thread"
java.lang.Exception: ThreadDump for thread "Signal Dispatcher"
```
or it could be some thread / job is not started (yet) so we don't see it but test waits for it - however, I don't see where.

**Comment by HeikoKlare** [comment]
I have not seen this failure for a long time and no other occurrences have been reported/linked.
