### ISSUE TITLE
Random failing BreakpointTests.testDeferredBreakpointsSepVM

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#678]
Failed in [this build](https://github.com/eclipse-platform/eclipse.platform/actions/runs/6158974241/job/16712844043#step:7:27530) of https://github.com/eclipse-platform/eclipse.platform/pull/666

```java
org.eclipse.ant.tests.ui.debug.BreakpointTests.testDeferredBreakpointsSepVM -- Time elapsed: 4.353 s <<< FAILURE!
junit.framework.AssertionFailedError: suspended, but not by breakpoint
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertNotNull(Assert.java:256)
	at junit.framework.TestCase.assertNotNull(TestCase.java:399)
	at org.eclipse.ant.tests.ui.debug.BreakpointTests.deferredBreakpoints(BreakpointTests.java:60)
```

**Comment by fedejeanne** [comment]
No reported failures in 1+ years. Closing.
