### ISSUE TITLE
Eclipse IDE 2022-06 crash on Fedora Linux 36;  WebKit2Gtk3 thread confusion

### ISSUE THREAD

**Issue by oh2mqk** [eclipse-platform/eclipse.platform#71]
The Fedora Linux 36 does no longer deliver Eclipse IDE as pre-packaged solution (last person managing it moved on to other things), and as a result we now have to download Eclipse provided package.  ( eclipse-java-2022-06-R-linux-gtk-x86_64.tar.gz )

Eclipse takes my workspace (created with older eclipse versions), and opens up all projects as expected.
However when I then select a method and press Control-Shift-G to look for callers of method of interest, nothing seems to happen for a bit, and soon all eclipse windows close.  There is a backtrace left behind, and I can extract a backtrace.

If I do the search command within a couple seconds of Eclipse startup, it will succeed.
Then I can go to caller of that method, and search again.
There seem to be a vague correlation with idle wait time before each search attempt.
Longer idle is more likely to trigger this behaviour -- but it can happen also with very short idle times.

Specifically when I wait about 5 seconds after Exclipse UI startup that has loaded the workspace,  I get the crash immediately, and it is always similar to what is below.  All I do is to move the mouse cursor on top of any function name in editor, and right-click on it -> crash.

The problem seem to be at following location:
```
#5  WebKit::allDataStores () at /usr/src/debug/webkit2gtk3-2.36.5-1.fc36.x86_64/Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.cpp:101
101         RELEASE_ASSERT(isUIThread());
```
However, that one is essentially telling that the runtime apparently switches threads when executing things.

```
(gdb) where
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007f7a7b88ecb3 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007f7a7b83e9c6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007f7a7b8287f4 in __GI_abort () at abort.c:79
#4  0x00007f77a986d5cb in WTFCrashWithInfo(int, char const*, char const*, int) () at /usr/src/debug/webkit2gtk3-2.36.5-1.fc36.x86_64/redhat-linux-build/WTF/Headers/wtf/Assertions.h:741
#5  WebKit::allDataStores() () at /usr/src/debug/webkit2gtk3-2.36.5-1.fc36.x86_64/Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.cpp:101
#6  0x00007f77a9bee7c0 in WebKit::WebsiteDataStore::forEachWebsiteDataStore(WTF::Function<void (WebKit::WebsiteDataStore&)>&&) (function=...) at /usr/src/debug/webkit2gtk3-2.36.5-1.fc36.x86_64/Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.cpp:108
#7  0x00007f77a9b728a7 in WebKit::WebProcessPool::registerURLSchemeAsSecure(WTF::String const&) (urlScheme=<optimized out>, this=<optimized out>) at /usr/include/c++/12/bits/unique_ptr.h:189
#8  registerSecurityPolicyForURIScheme(WebKitSecurityManager*, char const*, SecurityPolicy) (manager=<optimized out>, scheme=<optimized out>, policy=<optimized out>) at /usr/src/debug/webkit2gtk3-2.36.5-1.fc36.x86_64/Source/WebKit/UIProcess/API/glib/WebKitSecurityManager.cpp:93
#9  0x00007f77a9ba0bd2 in WebKit::WebKitProtocolHandler::WebKitProtocolHandler(_WebKitWebContext*) (context=<optimized out>, this=0x7f789fcff030) at /usr/src/debug/webkit2gtk3-2.36.5-1.fc36.x86_64/Source/WebKit/UIProcess/API/glib/WebKitProtocolHandler.cpp:92
#10 std::make_unique<WebKit::WebKitProtocolHandler, _WebKitWebContext*&>(_WebKitWebContext*&) () at /usr/include/c++/12/bits/unique_ptr.h:1065
#11 WTF::makeUnique<WebKit::WebKitProtocolHandler, _WebKitWebContext*&>(_WebKitWebContext*&) () at /usr/src/debug/webkit2gtk3-2.36.5-1.fc36.x86_64/redhat-linux-build/WTF/Headers/wtf/StdLibExtras.h:540
#12 webkitWebContextConstructed(GObject*) (object=<optimized out>) at /usr/src/debug/webkit2gtk3-2.36.5-1.fc36.x86_64/Source/WebKit/UIProcess/API/glib/WebKitWebContext.cpp:444
#13 0x00007f7a4c0bdf4c in g_object_new_internal (class=0x7f7a767b7080, params=params@entry=0x0, n_params=n_params@entry=0) at ../gobject/gobject.c:2053
#14 0x00007f7a4c0bf081 in g_object_new_with_properties (object_type=0x7f7a767b6f90 [None], n_properties=0, names=names@entry=0x0, values=values@entry=0x0) at ../gobject/gobject.c:2181
#15 0x00007f7a4c0bfb21 in g_object_new (object_type=<optimized out>, first_property_name=<optimized out>) at ../gobject/gobject.c:1821
#16 0x00007f77a9b80669 in createDefaultWebContext(gpointer) () at /usr/src/debug/webkit2gtk3-2.36.5-1.fc36.x86_64/Source/WebKit/UIProcess/API/glib/WebKitWebContext.cpp:689
#17 0x00007f7a3d73c6e5 in g_once_impl (once=0x7f77abf4ef00 <webkit_web_context_get_default::onceInit>, func=0x7f77a9b80600 <createDefaultWebContext(gpointer)>, arg=0x0) at ../glib/gthread.c:640
#18 0x00007f77a9b806f5 in webkit_web_context_get_default() () at /usr/src/debug/webkit2gtk3-2.36.5-1.fc36.x86_64/Source/WebKit/UIProcess/API/glib/WebKitWebContext.cpp:703
#19 0x00007f79e9c05e8c in Java_org_eclipse_swt_internal_webkit_WebKitGTK_webkit_1web_1context_1get_1default () at /opt/eclipse202206/configuration/org.eclipse.osgi/321/0/.cp/libswt-webkit-gtk-4952r11.so
#20 0x00007f7a6180d53a in  ()
#21 0x00007f7a6180d276 in  ()
#22 0x00007f7a7a31f1f8 in  ()
#23 0x00007f77f85b9368 in  ()
#24 0x00007f7a7a31f258 in  ()
#25 0x00007f77f85bb180 in  ()
#26 0x0000000000000000 in  ()
```

**Comment by akurtakov** [comment]
This is a bug in webkit package itself. Please install the one from updates-testing https://bodhi.fedoraproject.org/updates/FEDORA-2022-db51316d38 and eclipse will be back to working.
