### ISSUE TITLE
CVS commit throws NoSuchMethodException 

### ISSUE THREAD

**Issue by mpirmez** [eclipse-platform/eclipse.platform#72]
While commiting my changes to the CVS repository an error popup shows with the following content:

An internal error occurred during: "Committing resources".
'void org.eclipse.team.internal.core.subscribers.BatchingLock$ThreadInfo.<init>(org.eclipse.team.internal.core.subscribers.BatchingLock, org.eclipse.team.internal.core.subscribers.BatchingLock$IFlushOperation)'

The following stacktrace appears in the error log:
```
java.lang.NoSuchMethodError: 'void org.eclipse.team.internal.core.subscribers.BatchingLock$ThreadInfo.<init>(org.eclipse.team.internal.core.subscribers.BatchingLock, org.eclipse.team.internal.core.subscribers.BatchingLock$IFlushOperation)'
	at org.eclipse.team.internal.ccvs.core.syncinfo.ReentrantLock$CVSThreadInfo.<init>(ReentrantLock.java:43)
	at org.eclipse.team.internal.ccvs.core.syncinfo.ReentrantLock.createThreadInfo(ReentrantLock.java:69)
	at org.eclipse.team.internal.core.subscribers.BatchingLock.acquire(BatchingLock.java:269)
	at org.eclipse.team.internal.ccvs.core.resources.EclipseSynchronizer.beginBatching(EclipseSynchronizer.java:485)
	at org.eclipse.team.internal.ccvs.core.resources.EclipseSynchronizer.run(EclipseSynchronizer.java:1473)
	at org.eclipse.team.internal.ccvs.core.resources.EclipseResource.lambda$1(EclipseResource.java:260)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.team.internal.ccvs.core.resources.EclipseResource.run(EclipseResource.java:258)
	at org.eclipse.team.internal.ccvs.core.client.Command.execute(Command.java:339)
	at org.eclipse.team.internal.ccvs.core.client.Command.execute(Command.java:805)
	at org.eclipse.team.internal.ccvs.ui.operations.CommitOperation.executeCommand(CommitOperation.java:42)
	at org.eclipse.team.internal.ccvs.ui.operations.SingleCommandOperation.execute(SingleCommandOperation.java:45)
	at org.eclipse.team.internal.ccvs.ui.operations.RepositoryProviderOperation.execute(RepositoryProviderOperation.java:285)
	at org.eclipse.team.internal.ccvs.ui.operations.SingleCommandOperation.execute(SingleCommandOperation.java:69)
	at org.eclipse.team.internal.ccvs.ui.operations.RepositoryProviderOperation.execute(RepositoryProviderOperation.java:259)
	at org.eclipse.team.internal.ccvs.ui.operations.RepositoryProviderOperation.execute(RepositoryProviderOperation.java:212)
	at org.eclipse.team.internal.ccvs.ui.operations.CVSOperation.run(CVSOperation.java:85)
	at org.eclipse.team.internal.ccvs.ui.wizards.CommitWizard$AddAndCommitOperation.execute(CommitWizard.java:112)
	at org.eclipse.team.internal.ccvs.ui.operations.CVSOperation.run(CVSOperation.java:85)
	at org.eclipse.team.internal.ui.actions.JobRunnableContext.run(JobRunnableContext.java:155)
	at org.eclipse.team.internal.ui.actions.JobRunnableContext$ResourceJob.runInWorkspace(JobRunnableContext.java:83)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I'm using eclipse 2022-06 and Eclipse CVS Client 1.4.800.v20190307-0500

**Comment by akurtakov** [comment]
I wonder how did you manage to get CVS plugin installed on top of 2022-06 as it's no longer part of this release.

**Comment by mpirmez** [comment]
It was downloaded from http://download.eclipse.org/releases/2019-03
I realized now that this is a really old repository.
I'm now using Eclipse CVS Client 1.4.2000.v20211124-1800 from http://download.eclipse.org/releases/2021-12/ and the issue seems fixed.
I'm closing the issue.

**Comment by akurtakov** [comment]
Please note that CVS plugin has been removed from master and is no longer maintained and may stop working at any time .
