### ISSUE TITLE
Random failing JobTest.testJoinWithCancelingMonitor

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#744]
Test test `org.eclipse.core.tests.runtime.jobs.JobTest.testJoinWithCancelingMonitor` is randomly failing, e.g., https://github.com/eclipse-platform/eclipse.platform/pull/737/checks?check_run_id=17676558920.

```
junit.framework.AssertionFailedError: 2.0 expected:<4> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:377)
	at org.eclipse.core.tests.runtime.jobs.JobTest.testJoinWithCancelingMonitor(JobTest.java:1004)
```

See #320. #402 for previous, probably related failures.

**Comment by HeikoKlare** [comment]
Still failing randomly in the same state and with the same output: https://github.com/eclipse-platform/eclipse.platform/pull/1021/checks?check_run_id=19707210567
