### ISSUE TITLE
Failure of some tests in ProcessConsoleTests

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#770]
See https://github.com/eclipse-platform/eclipse.platform/pull/766/checks?check_run_id=18039630262

```java
array lengths differed, expected.length=1 actual.length=0; arrays first differed at element [0]; expected:<-84> but was:<end of array>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:89)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)
	at org.junit.Assert.internalArrayEquals(Assert.java:534)
	at org.junit.Assert.assertArrayEquals(Assert.java:343)
	at org.junit.Assert.assertArrayEquals(Assert.java:354)
	at org.eclipse.debug.tests.console.ProcessConsoleTests.testBinaryOutputToFile(ProcessConsoleTests.java:491)
```

and in https://github.com/eclipse-platform/eclipse.platform/actions/runs/6639804748/job/18080581872?pr=766

```java
org.junit.ComparisonFailure: Wrong content in line 0 expected:<['Native' process started.]> but was:<[]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.eclipse.debug.tests.console.ProcessConsoleTests.testOutput(ProcessConsoleTests.java:448)
```

**Comment by jukzi** [comment]
Failed also with "Wrong content in line 0 expected" during 
https://github.com/eclipse-platform/eclipse.platform/pull/764/checks?check_run_id=18290526329
