### ISSUE TITLE
Failure of some tests in LogSerializationTest

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#771]
See https://github.com/eclipse-platform/eclipse.platform/pull/766/checks?check_run_id=18039630262

```java
1.1 different number of statuses expected:<10> but was:<12>
junit.framework.AssertionFailedError: 1.1 different number of statuses expected:<10> but was:<12>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:377)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.assertEquals(LogSerializationTest.java:52)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.doTest(LogSerializationTest.java:156)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.testMultiMultiStatusSerialize(LogSerializationTest.java:197)
```

and 

```java
1.0 different number of statuses expected:<1> but was:<13>
junit.framework.AssertionFailedError: 1.0 different number of statuses expected:<1> but was:<13>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:377)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.assertEquals(LogSerializationTest.java:52)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.doTest(LogSerializationTest.java:156)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.doTest(LogSerializationTest.java:160)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.testDeepMultiStatus(LogSerializationTest.java:187)
```

and

```java
1.1 different number of statuses expected:<5> but was:<18>
junit.framework.AssertionFailedError: 1.1 different number of statuses expected:<5> but was:<18>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:377)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.assertEquals(LogSerializationTest.java:52)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.doTest(LogSerializationTest.java:156)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.testMultiSerialize(LogSerializationTest.java:207)
```

and

```java
1.0 different number of statuses expected:<1> but was:<19>
junit.framework.AssertionFailedError: 1.0 different number of statuses expected:<1> but was:<19>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at junit.framework.TestCase.assertEquals(TestCase.java:377)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.assertEquals(LogSerializationTest.java:52)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.doTest(LogSerializationTest.java:156)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.doTest(LogSerializationTest.java:160)
	at org.eclipse.core.tests.internal.runtime.LogSerializationTest.testSimpleSerialize(LogSerializationTest.java:221)
```

**Comment by fedejeanne** [comment]
No reported failures in 1+ years. Closing.
