### ISSUE TITLE
SymlinkTest fails on Windows after converting to JUnit 4

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform#783]
See https://download.eclipse.org/eclipse/downloads/drops4/I20231027-0140/testresults/html/org.eclipse.core.tests.resources_ep430I-unit-win32-java17_win32.win32.x86_64_17.html

Most likely regression from 826efd662897718e6e9fca4663819f57ba9564b5.

@HeikoKlare : please check.

```
Multiple Failures (2 failures) org.junit.TestCouldNotBeSkippedException: Test could not be skipped due to other failures java.lang.NullPointerException: Cannot invoke "org.eclipse.core.filesystem.IFileStore.delete(int, org.eclipse.core.runtime.IProgressMonitor)" because "this.localFileBaseStore" is null

org.opentest4j.MultipleFailuresError: Multiple Failures (2 failures)
org.junit.TestCouldNotBeSkippedException: Test could not be skipped due to other failures
java.lang.NullPointerException: Cannot invoke "org.eclipse.core.filesystem.IFileStore.delete(int, org.eclipse.core.runtime.IProgressMonitor)" because "this.localFileBaseStore" is null
Suppressed: org.junit.TestCouldNotBeSkippedException: Test could not be skipped due to other failures
Caused by: org.junit.AssumptionViolatedException: Can't create symbolic links in this platform: win32
at org.junit.Assume.assumeTrue(Assume.java:68)
at org.eclipse.core.tests.filesystem.SymlinkTest.setUp(SymlinkTest.java:106)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Suppressed: java.lang.NullPointerException: Cannot invoke "org.eclipse.core.filesystem.IFileStore.delete(int, org.eclipse.core.runtime.IProgressMonitor)" because "this.localFileBaseStore" is null
at org.eclipse.core.tests.filesystem.FileSystemTest.tearDown(FileSystemTest.java:101)
at org.eclipse.core.tests.filesystem.SymlinkTest.tearDown(SymlinkTest.java:116)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by HeikoKlare** [comment]
Yes, it's a regression from #755. I propose to properly restructure the FileSystemTests to avoid the complex and error-prone setup/teardown inheritance coming from the original JUnit 3 implementation, which is not necessary with JUnit 4/5 anymore. I started PR #785 for that.
