### ISSUE TITLE
Failure of org.eclipse.debug.tests.console.IOConsoleFixedWidthTests.testManyPartitions

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#861]
Failed in [this build](https://github.com/eclipse-platform/eclipse.platform/actions/runs/6889164825/job/18739620826?pr=860) of #860 

```java
org.eclipse.debug.tests.console.IOConsoleFixedWidthTests.testManyPartitions -- Time elapsed: 6.823 s <<< FAILURE!
java.lang.AssertionError: Test triggered errors in IOConsole
	at org.eclipse.debug.tests.console.IOConsoleTests.lambda$1(IOConsoleTests.java:128)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037)
	at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054)
	at org.eclipse.debug.tests.console.IOConsoleTests.assertNoError(IOConsoleTests.java:126)
	at org.eclipse.debug.tests.console.IOConsoleTests.tearDown(IOConsoleTests.java:122)
...
```

**Comment by fedejeanne** [comment]
No reported failures in 1+ years. Closing.
