### ISSUE TITLE
[Windows] Failure of org.eclipse.debug.tests.console.RuntimeProcessTests.testProcessTerminated

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform#863]
It failed in [this Windows build](https://github.com/eclipse-platform/eclipse.platform/actions/runs/6891569574/job/18746911435?pr=862) of #862 

```java
org.eclipse.debug.tests.console.RuntimeProcessTests.testProcessTerminated -- Time elapsed: 1.138 s <<< FAILURE!
java.lang.AssertionError: RuntimePocess not terminated.
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.debug.tests.TestUtil.waitWhile(TestUtil.java:138)
	at org.eclipse.debug.tests.console.RuntimeProcessTests.testProcessTerminated(RuntimeProcessTests.java:67)
...
```

**Comment by HeikoKlare** [comment]
The problem affects multiple tests in `RuntimeProcessTests`. They are failing quite often recently, e.g., https://github.com/eclipse-platform/eclipse.platform/actions/runs/7145955687/job/19463184753

testTerminateProcessWithSubProcesses (org.eclipse.debug.tests.console.RuntimeProcessTests):
```
RuntimePocess not terminated.
java.lang.AssertionError: RuntimePocess not terminated.
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.debug.tests.TestUtil.waitWhile(TestUtil.java:138)
	at org.eclipse.debug.tests.console.RuntimeProcessTests.testTerminateProcessWithSubProcesses(RuntimeProcessTests.java:132)
```

testProcessTerminated (org.eclipse.debug.tests.console.RuntimeProcessTests):
```
RuntimePocess not terminated.
java.lang.AssertionError: RuntimePocess not terminated.
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.debug.tests.TestUtil.waitWhile(TestUtil.java:138)
	at org.eclipse.debug.tests.console.RuntimeProcessTests.testProcessTerminated(RuntimeProcessTests.java:67)
```

**Comment by fedejeanne** [comment]
The test seems stable since #1036 was merged. Thank you!
