### ISSUE TITLE
NPE in ContentMergeViewer

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform#868]
```
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.ToolBar.getParent()" because the return value of "org.eclipse.jface.action.ToolBarManager.getControl()" is null
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.lambda$5(ContentMergeViewer.java:811)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4046)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3662)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:645)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:342)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:552)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
```
eclipse.buildId=4.30.0.I20231119-1800
java.version=21

**Comment by jukzi** [comment]
that code was recently changed: cfba1995a8302bc1e9402fd5da9fbcac6ab97d3c
https://github.com/eclipse-platform/eclipse.platform/pull/732
@zulus @sratz

**Comment by iloveeclipse** [comment]
Any steps to reproduce?

**Comment by jukzi** [comment]
don't now how to reproduce. And as it is async now it' probably a timing problem with async dispose

**Comment by sratz** [comment]
> don't now how to reproduce. And as it is async now it' probably a timing problem with async dispose

yes, at the very least an `isDispoed()` check needs to be performed in the async exec.

However, see my questions here https://github.com/eclipse-platform/eclipse.platform/pull/732#discussion_r1383011960, I have more concerns about that change.

It has changed

```
tbm.getControl().getParent().layout(true);
```
to
```
tbm.getControl().getParent().setRedraw(true);
```
with no apparent justification (isn't `setRedraw(true)` basically a no-op, as it was neve set to `false`?).

It feels like a wrong fix for the problem and asyncExec() feels like the wrong workaround.

Maybe #732 should be reverted altogether and investigated again next release?

**Comment by HeikoKlare** [comment]
> (isn't `setRedraw(true)` basically a no-op, as it was neve set to `false`?

@sratz I just stepped over the changes of #732 when applying a refactoring to `setRedraw` calls and found that #732 seems to have introduced the only place in platform code at which `setRedraw(true)` is called without a previous `setRedraw(false)`, 
Since that method uses an internal counter for the number of calls to the method (with `false` counting up and `true` counting down), not using `setRedraw` in a pair (once with `false`, once with `true`) seems to be dangerous to me. In this case it may lead to the situation that disabling redraw will never work again, because set `setRedraw(true)` call makes the counter negative, from which is may never recover.

In combination with the other concerns, I would highly recommend merging #869, but since it's already RC2 signoff, it seems to be too late for 2023-12 release, isn't it?
