### ISSUE TITLE
Random failing org.eclipse.core.internal.expressions.tests.ExpressionTests.testSubTypeTiming 

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#894]
Failed once on MacOS: https://github.com/eclipse-platform/eclipse.platform/pull/892/checks?check_run_id=19130535605

```
cachedDelta: 90, instanceDelta: 73
java.lang.AssertionError: cachedDelta: 90, instanceDelta: 73
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.core.internal.expressions.tests.ExpressionTests.testSubTypeTiming(ExpressionTests.java:1135)
```

**Comment by akurtakov** [comment]
Is this really timing measured ? If that's the case the test needs to be changed to check results and not timing.

**Comment by HeikoKlare** [comment]
> Is this really timing measured ? If that's the case the test needs to be changed to check results and not timing.

It seems to be an attempt to provide a performance test for a caching mechanism. So you are right: it has to be rewritten to make a functional validation of the caching rather than a time-based one.

**Comment by jukzi** [comment]
mac
```
cachedDelta: 148, instanceDelta: 74
java.lang.AssertionError: cachedDelta: 148, instanceDelta: 74
	at org.eclipse.core.internal.expressions.tests.ExpressionTests.testSubTypeTiming(ExpressionTests.java:1135)
```
https://github.com/eclipse-platform/eclipse.platform/pull/918/checks?check_run_id=19294549887

**Comment by jukzi** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20250116-1800/testresults/html/org.eclipse.core.expressions.tests_ep435I-unit-macosx-x86_64-java21_macosx.cocoa.x86_64_21.html

```
java.lang.AssertionError: [assert cachedDelta is less than instanceDelta43]
Expecting actual:
55L
to be less than:
43L
at org.eclipse.core.internal.expressions.tests.ExpressionTests.testSubTypeTiming(ExpressionTests.java:1036)
```
